import type { LandingLocale } from "@/lib/landing-content"

import type { LocalizedDebtCopy } from "../../components/debt-feature-types"

export const receivableDialogCopy = {
  en: {
    addTitle: "Add customer receivable",
    addBtn: "Add Receivable",
    addDescription: "Record an amount a customer still owes the business.",
    searchPlaceholder: "Search customer receivables...",
    showing: "Showing",
    sort: "Sort",
    ascending: "Ascending",
    descending: "Descending",
    loadingTitle: "Loading receivables...",
    loadingDescription:
      "Customer receivable records are loading from the server.",
    loadErrorTitle: "Unable to load receivables",
    emptyTitle: "No receivables yet",
    emptyDescription:
      "Debt-marked sales and manual customer debts will appear here.",
    noResultsTitle: "No matching receivables",
    noResultsDescription: "Try changing your search term or due-date filter.",
    statsPaid: "Paid",
    statsNotPaid: "Not paid",
    statsDue: "Due",
    statsDueWithin: "Due soon",
    dueFilter: "Due filter",
    allDueDates: "All due dates",
    dueNow: "Due / overdue",
    within1Day: "1 day left",
    within3Days: "3 days left",
    within7Days: "7 days left",
    within31Days: "31 days left",
    within186Days: "6 months left",
    within366Days: "1 year left",
    viewTitle: "Receivable details",
    viewDescription: "Customer balance, payment, and source details.",
    partyName: "Customer",
    partyNamePlaceholder: "Enter customer name",
    partyPhone: "Customer phone",
    partyPhonePlaceholder: "Enter customer phone (optional)",
    referenceNumber: "Reference number",
    referenceNumberPlaceholder: "Sale or other reference (optional)",
    totalAmount: "Total debt",
    amountPaid: "Amount received",
    balanceAmount: "Balance receivable",
    status: "Payment status",
    debtDate: "Debt date",
    debtDateTodayToggle: "Debt date is today",
    debtDateTodayDescription:
      "Keep this checked to use today's date, or uncheck it to select another debt start date.",
    dueDate: "Debt end date",
    source: "Sale",
    manualEntry: "Manual entry",
    notes: "Notes",
    notesPlaceholder: "Add collection terms or follow-up notes",
    createdBy: "Recorded by",
    createdAt: "Created at",
    statusPending: "Pending",
    statusPartial: "Partially paid",
    statusPaid: "Paid",
    cancel: "Cancel",
    create: "Save Receivable",
    close: "Close",
    actions: "Actions",
    openActions: "Open receivable actions",
    createSuccess: "Receivable record was created.",
    deleteTitle: "Delete receivable record?",
    deleteDescription:
      "This removes the debt record but does not delete its linked sale.",
    confirmDelete: "Delete",
    deleteSuccess: "Receivable record was deleted.",
    deleteError: "Failed to delete receivable record.",
    validation: {
      partyRequired: "Enter the customer name.",
      totalRequired: "Total debt must be greater than 0.",
      amountPaidInvalid:
        "Amount received must be between 0 and the total debt.",
      debtDateRequired: "Select the debt date.",
      dueDateBeforeDebtDate: "Due date cannot be earlier than the debt date.",
    },
  },
  sw: {
    addTitle: "Ongeza deni la mteja",
    addBtn: "Ongeza Deni la Kudai",
    addDescription: "Rekodi kiasi ambacho mteja bado anadaiwa na biashara.",
    searchPlaceholder: "Tafuta madeni ya wateja...",
    showing: "Onyesha",
    sort: "Panga",
    ascending: "Kupanda",
    descending: "Kushuka",
    loadingTitle: "Madeni ya kudai yanapakiwa...",
    loadingDescription:
      "Rekodi za madeni ya wateja zinapakiwa kutoka kwenye seva.",
    loadErrorTitle: "Imeshindikana kupakia madeni ya kudai",
    emptyTitle: "Hakuna madeni ya kudai bado",
    emptyDescription:
      "Mauzo ya deni na madeni yaliyowekwa moja kwa moja yataonekana hapa.",
    noResultsTitle: "Hakuna deni linalolingana",
    noResultsDescription:
      "Jaribu kubadilisha utafutaji au kichujio cha tarehe.",
    statsPaid: "Yaliyolipwa",
    statsNotPaid: "Hayajalipwa",
    statsDue: "Yamefika muda",
    statsDueWithin: "Yanayokaribia",
    dueFilter: "Chuja kwa muda",
    allDueDates: "Tarehe zote",
    dueNow: "Yamefika / yamechelewa",
    within1Day: "Imebaki siku 1",
    within3Days: "Zimebaki siku 3",
    within7Days: "Zimebaki siku 7",
    within31Days: "Zimebaki siku 31",
    within186Days: "Imebaki miezi 6",
    within366Days: "Umebaki mwaka 1",
    viewTitle: "Maelezo ya deni la kudai",
    viewDescription: "Salio la mteja, malipo, na chanzo cha deni.",
    partyName: "Mteja",
    partyNamePlaceholder: "Weka jina la mteja",
    partyPhone: "Simu ya mteja",
    partyPhonePlaceholder: "Weka simu ya mteja (si lazima)",
    referenceNumber: "Namba ya rejea",
    referenceNumberPlaceholder: "Mauzo au rejea nyingine (si lazima)",
    totalAmount: "Jumla ya deni",
    amountPaid: "Kiasi kilichopokelewa",
    balanceAmount: "Salio la kudai",
    status: "Hali ya malipo",
    debtDate: "Tarehe ya deni",
    debtDateTodayToggle: "Tarehe ya deni ni leo",
    debtDateTodayDescription:
      "Acha tiki ili kutumia tarehe ya leo, au ondoa tiki kuchagua tarehe nyingine ya kuanza kwa deni.",
    dueDate: "Tarehe ya mwisho ya deni",
    source: "Mauzo",
    manualEntry: "Imewekwa moja kwa moja",
    notes: "Maelezo ya ziada",
    notesPlaceholder: "Weka masharti ya makusanyo au maelezo ya ufuatiliaji",
    createdBy: "Imerekodiwa na",
    createdAt: "Tarehe ya kuundwa",
    statusPending: "Inasubiri",
    statusPartial: "Imelipwa sehemu",
    statusPaid: "Imelipwa",
    cancel: "Ghairi",
    create: "Hifadhi Deni",
    close: "Funga",
    actions: "Vitendo",
    openActions: "Fungua vitendo vya deni la kudai",
    createSuccess: "Deni la kudai limeundwa.",
    deleteTitle: "Futa deni hili la kudai?",
    deleteDescription:
      "Hatua hii itaondoa deni bila kufuta mauzo yaliyounganishwa.",
    confirmDelete: "Futa",
    deleteSuccess: "Deni la kudai limefutwa.",
    deleteError: "Imeshindikana kufuta deni la kudai.",
    validation: {
      partyRequired: "Weka jina la mteja.",
      totalRequired: "Jumla ya deni lazima iwe zaidi ya 0.",
      amountPaidInvalid:
        "Kiasi kilichopokelewa lazima kiwe kati ya 0 na jumla ya deni.",
      debtDateRequired: "Chagua tarehe ya deni.",
      dueDateBeforeDebtDate:
        "Tarehe ya mwisho haiwezi kuwa kabla ya tarehe ya deni.",
    },
  },
} as const satisfies LocalizedDebtCopy

export type ReceivableDialogCopy = (typeof receivableDialogCopy)[LandingLocale]
