import type { LandingLocale } from "@/lib/landing-content"

export const userDialogCopy = {
  en: {
    addTitle: "Add user",
    addDescription: "Create a user and define their workspace access.",
    editTitle: "Edit user",
    editDescription: "Update this user's profile and access.",
    viewTitle: "User details",
    viewDescription: "Profile and workspace access information.",
    firstName: "First name",
    firstNamePlaceholder: "Enter first name",
    lastName: "Last name",
    lastNamePlaceholder: "Enter last name",
    email: "Email address",
    emailPlaceholder: "Enter email address",
    phone: "Phone number",
    phonePlaceholder: "Enter phone number",
    role: "Role",
    status: "Status",
    password: "Password",
    passwordPlaceholder: "Enter password",
    passwordOptional: "New password (optional)",
    passwordHint: "Leave blank to keep the current password.",
    admin: "Admin",
    user: "User",
    active: "Active",
    inactive: "Inactive",
    createdAt: "Created at",
    cancel: "Cancel",
    create: "Create user",
    save: "Save changes",
    close: "Close",
    createSuccess: (name: string) => `${name} was created.`,
    updateSuccess: (name: string) => `${name} was updated.`,
    deleteTitle: "Delete this user?",
    deleteDescription: (name: string) =>
      `You are about to remove ${name} from this workspace. This action cannot be undone.`,
    bulkDeleteTitle: "Delete selected users?",
    bulkDeleteDescription: (count: number) =>
      `You are about to remove ${count} selected users. This action cannot be undone.`,
    confirmDelete: "Delete",
    deleteSuccess: (name: string) => `${name} was deleted.`,
    bulkDeleteSuccess: (count: number) =>
      `${count} selected users were deleted.`,
    validation: {
      firstNameRequired: "Enter the first name.",
      firstNameLength: "First name must be at least 2 characters.",
      lastNameRequired: "Enter the last name.",
      lastNameLength: "Last name must be at least 2 characters.",
      emailRequired: "Enter the email address.",
      emailInvalid: "Enter a valid email address.",
      phoneRequired: "Enter the phone number.",
      phoneInvalid: "Enter a valid phone number.",
      roleRequired: "Select a role.",
      passwordRequired: "Enter a password.",
      passwordLength: "Password must be at least 8 characters.",
      passwordUppercase: "Password must contain an uppercase letter.",
      passwordNumber: "Password must contain a number.",
    },
  },
  sw: {
    addTitle: "Ongeza mtumiaji",
    addDescription: "Fungua akaunti na uweke ruhusa zake za eneo la kazi.",
    editTitle: "Hariri mtumiaji",
    editDescription: "Sasisha wasifu na ruhusa za mtumiaji huyu.",
    viewTitle: "Taarifa za mtumiaji",
    viewDescription: "Wasifu na taarifa za ruhusa za eneo la kazi.",
    firstName: "Jina la kwanza",
    firstNamePlaceholder: "Weka jina la kwanza",
    lastName: "Jina la mwisho",
    lastNamePlaceholder: "Weka jina la mwisho",
    email: "Barua pepe",
    emailPlaceholder: "Weka barua pepe",
    phone: "Namba ya simu",
    phonePlaceholder: "Weka namba ya simu",
    role: "Wajibu",
    status: "Hali",
    password: "Nenosiri",
    passwordPlaceholder: "Weka nenosiri",
    passwordOptional: "Nenosiri jipya (si lazima)",
    passwordHint: "Acha wazi ili kubaki na nenosiri la sasa.",
    admin: "Msimamizi",
    user: "Mtumiaji",
    active: "Anatumika",
    inactive: "Hatumiki",
    createdAt: "Tarehe ya kuundwa",
    cancel: "Ghairi",
    create: "Ongeza mtumiaji",
    save: "Hifadhi mabadiliko",
    close: "Funga",
    createSuccess: (name: string) => `${name} ameongezwa.`,
    updateSuccess: (name: string) => `${name} amesasishwa.`,
    deleteTitle: "Futa mtumiaji huyu?",
    deleteDescription: (name: string) =>
      `Unakaribia kumwondoa ${name} kwenye eneo hili. Hatua hii haiwezi kutenduliwa.`,
    bulkDeleteTitle: "Futa watumiaji waliochaguliwa?",
    bulkDeleteDescription: (count: number) =>
      `Unakaribia kuwaondoa watumiaji ${count}. Hatua hii haiwezi kutenduliwa.`,
    confirmDelete: "Futa",
    deleteSuccess: (name: string) => `${name} amefutwa.`,
    bulkDeleteSuccess: (count: number) =>
      `Watumiaji ${count} waliochaguliwa wamefutwa.`,
    validation: {
      firstNameRequired: "Weka jina la kwanza.",
      firstNameLength: "Jina la kwanza liwe na angalau herufi 2.",
      lastNameRequired: "Weka jina la mwisho.",
      lastNameLength: "Jina la mwisho liwe na angalau herufi 2.",
      emailRequired: "Weka barua pepe.",
      emailInvalid: "Weka barua pepe halali.",
      phoneRequired: "Weka namba ya simu.",
      phoneInvalid: "Weka namba ya simu halali.",
      roleRequired: "Chagua wajibu.",
      passwordRequired: "Weka nenosiri.",
      passwordLength: "Nenosiri liwe na angalau herufi 8.",
      passwordUppercase: "Nenosiri liwe na angalau herufi moja kubwa.",
      passwordNumber: "Nenosiri liwe na angalau namba moja.",
    },
  },
} as const satisfies Record<LandingLocale, unknown>

export type UserDialogCopy = (typeof userDialogCopy)[LandingLocale]
