import type { LandingLocale } from "@/lib/landing-content"

export const dashboardOverviewCopy = {
  en: {
    kpis: {
      products: "Total parts",
      productsDetail: "Distinct product records",
      quantity: "Stock quantity",
      quantityDetail: "Units currently available",
      value: "Inventory value",
      valueDetail: "Current quantity multiplied by selling price",
      alerts: "Stock alerts",
      alertsDetail: "{low} low stock, {out} out of stock",
    },
    inventoryTrend: "Inventory movement",
    inventoryTrendDescription:
      "Actual quantities received and dispatched during the last nine months.",
    stockIn: "Stock in",
    stockOut: "Stock out",
    salesOverview: "Sales overview",
    thisMonth: "Current month",
    collectionRate: "Collection rate",
    collectionRateDetail: "Amount received against sales value",
    numberOfSales: "Sales records",
    totalSales: "Total sales",
    amountReceived: "Amount received",
    recentActivities: "Recent activities",
    noActivities: "No recent stock or sales activity.",
    alerts: "Alerts and notifications",
    viewNotifications: "View notifications",
    dueSoon: "Debts due within 3 days",
    lowStock: "Low-stock parts",
    outOfStock: "Out-of-stock parts",
    topProducts: "Top-selling parts",
    last30Days: "Last 30 days",
    noTopProducts: "No sales recorded in the last 30 days.",
    units: "units",
    revenue: "Revenue",
    loading: "Loading dashboard data",
    loadError: "Dashboard data could not be loaded.",
    refresh: "Refresh",
    retry: "Try again",
    activity: {
      SALE: "Sale recorded",
      SALE_DISPATCH: "Sale dispatched",
      INCOMING: "Stock received",
      OUTGOING: "Stock dispatched",
      detail: "{quantity} units · {reference}",
      noReference: "No reference",
    },
  },
  sw: {
    kpis: {
      products: "Jumla ya spea",
      productsDetail: "Rekodi tofauti za bidhaa",
      quantity: "Idadi ya stoo",
      quantityDetail: "Idadi iliyopo kwa sasa",
      value: "Thamani ya stoo",
      valueDetail: "Idadi ya sasa ikizidishwa kwa bei ya kuuza",
      alerts: "Tahadhari za stoo",
      alertsDetail: "Stoo ndogo {low}, zilizoisha {out}",
    },
    inventoryTrend: "Mzunguko wa stoo",
    inventoryTrendDescription:
      "Idadi halisi iliyopokelewa na iliyotoka katika miezi tisa iliyopita.",
    stockIn: "Zilizoingia",
    stockOut: "Zilizotoka",
    salesOverview: "Muhtasari wa mauzo",
    thisMonth: "Mwezi huu",
    collectionRate: "Kiwango cha makusanyo",
    collectionRateDetail: "Kiasi kilichopokelewa dhidi ya thamani ya mauzo",
    numberOfSales: "Rekodi za mauzo",
    totalSales: "Jumla ya mauzo",
    amountReceived: "Kiasi kilichopokelewa",
    recentActivities: "Shughuli za hivi karibuni",
    noActivities: "Hakuna shughuli za hivi karibuni za stoo au mauzo.",
    alerts: "Tahadhari na taarifa",
    viewNotifications: "Angalia taarifa",
    dueSoon: "Madeni ndani ya siku 3",
    lowStock: "Spea zenye stoo ndogo",
    outOfStock: "Spea zilizoisha stoo",
    topProducts: "Spea zinazouzwa zaidi",
    last30Days: "Siku 30 zilizopita",
    noTopProducts: "Hakuna mauzo yaliyorekodiwa katika siku 30 zilizopita.",
    units: "idadi",
    revenue: "Mapato",
    loading: "Inapakia taarifa za dashibodi",
    loadError: "Taarifa za dashibodi hazikuweza kupakiwa.",
    refresh: "Pakia upya",
    retry: "Jaribu tena",
    activity: {
      SALE: "Mauzo yamerekodiwa",
      SALE_DISPATCH: "Mauzo yametumwa",
      INCOMING: "Stoo imepokelewa",
      OUTGOING: "Stoo imetumwa",
      detail: "Idadi {quantity} · {reference}",
      noReference: "Hakuna kumbukumbu",
    },
  },
} as const satisfies Record<LandingLocale, object>
