import type { LandingLocale } from "@/lib/landing-content"

export const analyticsCopy = {
  en: {
    dateRange: "Reporting period",
    ranges: {
      "30": "Last 30 days",
      "90": "Last 90 days",
      "180": "Last 6 months",
      "365": "Last 12 months",
      all: "All time",
    },
    refresh: "Refresh",
    loadingTitle: "Preparing business analytics",
    loadingDescription:
      "Sales, inventory, stock movements, and debts are being summarized.",
    errorTitle: "Analytics could not be loaded",
    retry: "Try again",
    noData: "No data is available for this period.",
    selectedPeriod: "Selected reporting period",
    currentSnapshot: "Current business snapshot",
    kpis: {
      salesRevenue: "Sales revenue",
      salesRevenueDetail: "From {count} sales records",
      unitsSold: "Units sold",
      unitsSoldDetail: "Across {count} product lines",
      inventoryValue: "Inventory value",
      inventoryValueDetail: "{count} parts currently in stock",
      receivableBalance: "Receivable balance",
      receivableBalanceDetail: "Money still owed by customers",
    },
    financialTrend: {
      title: "Revenue and purchasing trend",
      description:
        "Compare sales revenue against the cost of incoming stock over time.",
      revenue: "Sales revenue",
      cost: "Incoming stock cost",
    },
    stockMovement: {
      title: "Inventory movement",
      description: "Units entering the store compared with units dispatched.",
      stockIn: "Stock in",
      stockOut: "Stock out",
    },
    paymentMethods: {
      title: "Payment method mix",
      description: "How customers paid for sales in the selected period.",
      CASH: "Cash",
      MOBILE_MONEY: "Mobile money",
      BANK_TRANSFER: "Bank transfer",
      OTHER: "Other",
      UNKNOWN: "Not specified",
    },
    debtPosition: {
      title: "Debt position",
      description:
        "Compare the original debt value with paid and outstanding balances.",
      receivable: "Receivable",
      payable: "Payable",
      paid: "Paid",
      outstanding: "Outstanding",
    },
    topProducts: {
      title: "Top 10 selling parts",
      description:
        "Quantity trends for the ten best-selling parts in the selected period.",
      units: "units",
      totalPrice: "Total price",
    },
    reports: {
      eyebrow: "Download center",
      title: "Business reports",
      description:
        "Download spreadsheet-compatible CSV reports for review, sharing, or further analysis.",
      download: "Download CSV",
      rows: "{count} rows",
      periodNote: "Uses the selected reporting period",
      snapshotNote: "Uses the current inventory snapshot",
      success: "{name} downloaded successfully.",
      error: "The report could not be downloaded.",
      sales: {
        title: "Sales report",
        description:
          "Sales totals, customer details, payment status, and payment method.",
      },
      inventory: {
        title: "Inventory report",
        description:
          "Current part quantities, prices, categories, and stock status.",
      },
      movements: {
        title: "Stock movement report",
        description:
          "Incoming and outgoing stock records with quantities and values.",
      },
      debts: {
        title: "Debt report",
        description:
          "Receivable and payable balances, statuses, and due dates.",
      },
    },
    csv: {
      date: "Date",
      type: "Type",
      reference: "Reference",
      relatedDocument: "Related document",
      relatedParty: "Related party",
      customer: "Customer",
      creditor: "Creditor",
      supplier: "Supplier",
      contact: "Contact",
      handledBy: "Handled by",
      purpose: "Purpose",
      status: "Status",
      paymentMethod: "Payment method",
      totalAmount: "Total amount",
      amountPaid: "Amount paid",
      balance: "Balance",
      dueDate: "Due date",
      partNumber: "Part number",
      partName: "Part name",
      category: "Category",
      quantity: "Quantity",
      unitPrice: "Unit price",
      unitCost: "Unit cost",
      lineTotal: "Line total",
      stockValue: "Stock value",
      direction: "Direction",
      notes: "Notes",
      incoming: "Incoming",
      outgoing: "Outgoing",
      receivable: "Receivable",
      payable: "Payable",
      values: {
        PAID: "Paid",
        PARTIAL: "Partially paid",
        PENDING: "Pending",
        UNPAID: "Not paid",
        SALE: "Sale",
        DAMAGED: "Damaged",
        RETURN: "Return",
        in_stock: "In stock",
        low_stock: "Low stock",
        out_of_stock: "Out of stock",
      },
    },
  },
  sw: {
    dateRange: "Kipindi cha ripoti",
    ranges: {
      "30": "Siku 30 zilizopita",
      "90": "Siku 90 zilizopita",
      "180": "Miezi 6 iliyopita",
      "365": "Miezi 12 iliyopita",
      all: "Muda wote",
    },
    refresh: "Pakia upya",
    loadingTitle: "Inaandaa uchambuzi wa biashara",
    loadingDescription:
      "Mauzo, stoo, mizunguko ya bidhaa, na madeni yanajumlishwa.",
    errorTitle: "Uchambuzi haukuweza kupakiwa",
    retry: "Jaribu tena",
    noData: "Hakuna taarifa katika kipindi hiki.",
    selectedPeriod: "Kipindi cha ripoti kilichochaguliwa",
    currentSnapshot: "Hali ya biashara kwa sasa",
    kpis: {
      salesRevenue: "Mapato ya mauzo",
      salesRevenueDetail: "Kutoka rekodi {count} za mauzo",
      unitsSold: "Bidhaa zilizouzwa",
      unitsSoldDetail: "Katika mistari {count} ya bidhaa",
      inventoryValue: "Thamani ya stoo",
      inventoryValueDetail: "Spea {count} zilizopo stoo kwa sasa",
      receivableBalance: "Salio tunalodai",
      receivableBalanceDetail: "Fedha ambazo wateja bado wanadaiwa",
    },
    financialTrend: {
      title: "Mwelekeo wa mapato na manunuzi",
      description:
        "Linganisha mapato ya mauzo na gharama ya bidhaa zinazoingia kwa muda.",
      revenue: "Mapato ya mauzo",
      cost: "Gharama ya stoo inayoingia",
    },
    stockMovement: {
      title: "Mzunguko wa stoo",
      description: "Idadi inayoingia dukani ikilinganishwa na idadi inayotoka.",
      stockIn: "Stoo inayoingia",
      stockOut: "Stoo inayotoka",
    },
    paymentMethods: {
      title: "Mgawanyo wa njia za malipo",
      description:
        "Jinsi wateja walivyolipia mauzo katika kipindi kilichochaguliwa.",
      CASH: "Taslimu",
      MOBILE_MONEY: "Pesa kwa simu",
      BANK_TRANSFER: "Hamisho la benki",
      OTHER: "Nyingine",
      UNKNOWN: "Haijabainishwa",
    },
    debtPosition: {
      title: "Hali ya madeni",
      description:
        "Linganisha thamani ya awali ya deni na kiasi kilicholipwa na salio.",
      receivable: "Tunalodai",
      payable: "Tunalodaiwa",
      paid: "Kilicholipwa",
      outstanding: "Salio",
    },
    topProducts: {
      title: "Spea 10 zinazouzwa zaidi",
      description:
        "Mwelekeo wa idadi kwa spea kumi zinazouzwa zaidi katika kipindi kilichochaguliwa.",
      units: "idadi",
      totalPrice: "Bei ya jumla",
    },
    reports: {
      eyebrow: "Kituo cha upakuaji",
      title: "Ripoti za biashara",
      description:
        "Pakua ripoti za CSV zinazofunguka kwenye programu za lahajedwali kwa ukaguzi, ushirikishaji, au uchambuzi zaidi.",
      download: "Pakua CSV",
      rows: "Mistari {count}",
      periodNote: "Inatumia kipindi cha ripoti kilichochaguliwa",
      snapshotNote: "Inatumia hali ya sasa ya stoo",
      success: "{name} imepakuliwa.",
      error: "Ripoti haikuweza kupakuliwa.",
      sales: {
        title: "Ripoti ya mauzo",
        description:
          "Jumla za mauzo, taarifa za mteja, hali ya malipo, na njia ya malipo.",
      },
      inventory: {
        title: "Ripoti ya stoo",
        description:
          "Idadi za sasa, bei, makundi, na hali za spea kwenye stoo.",
      },
      movements: {
        title: "Ripoti ya mzunguko wa stoo",
        description:
          "Rekodi za bidhaa zinazoingia na kutoka pamoja na idadi na thamani.",
      },
      debts: {
        title: "Ripoti ya madeni",
        description:
          "Madeni tunayodai na tunayodaiwa, hali zake, na tarehe za mwisho.",
      },
    },
    csv: {
      date: "Tarehe",
      type: "Aina",
      reference: "Kumbukumbu",
      relatedDocument: "Hati inayohusiana",
      relatedParty: "Mhusika",
      customer: "Mteja",
      creditor: "Mkopeshaji",
      supplier: "Msambazaji",
      contact: "Mawasiliano",
      handledBy: "Aliyeshughulikia",
      purpose: "Sababu",
      status: "Hali",
      paymentMethod: "Njia ya malipo",
      totalAmount: "Jumla ya kiasi",
      amountPaid: "Kiasi kilicholipwa",
      balance: "Salio",
      dueDate: "Tarehe ya mwisho",
      partNumber: "Namba ya spea",
      partName: "Jina la spea",
      category: "Kundi",
      quantity: "Idadi",
      unitPrice: "Bei ya moja",
      unitCost: "Gharama ya moja",
      lineTotal: "Jumla ya mstari",
      stockValue: "Thamani ya stoo",
      direction: "Mwelekeo",
      notes: "Maelezo",
      incoming: "Inayoingia",
      outgoing: "Inayotoka",
      receivable: "Tunalodai",
      payable: "Tunalodaiwa",
      values: {
        PAID: "Imelipwa",
        PARTIAL: "Imelipwa kiasi",
        PENDING: "Inasubiri",
        UNPAID: "Haijalipwa",
        SALE: "Mauzo",
        DAMAGED: "Imeharibika",
        RETURN: "Imerejeshwa",
        in_stock: "Ipo stoo",
        low_stock: "Stoo ndogo",
        out_of_stock: "Imeisha stoo",
      },
    },
  },
} as const satisfies Record<LandingLocale, object>

export type AnalyticsCopy = (typeof analyticsCopy)[LandingLocale]
