import type { LandingLocale } from "@/lib/landing-content"

export const productDialogCopy = {
  en: {
    addTitle: "Add part",
    addDescription: "Create a new part record for inventory tracking.",
    editTitle: "Edit part",
    editDescription: "Update this part record and inventory details.",
    viewTitle: "Part details",
    viewDescription: "Review the current part record information.",
    partName: "Part name",
    partNamePlaceholder: "Enter part name",
    partNumber: "Part number",
    partNumberPlaceholder: "Enter part number",
    quantity: "Quantity",
    quantityPlaceholder: "Enter quantity",
    price: "Price",
    pricePlaceholder: "Enter price",
    image: "Part image",
    imageHelper: "Upload an optional image (JPEG, PNG, GIF, WebP) up to 5 MB.",
    currentImage: "Current image",
    category: "Category",
    uncategorized: "Uncategorized",
    status: "Status",
    inStock: "In stock",
    lowStock: "Low stock",
    outOfStock: "Out of stock",
    createdAt: "Created at",
    cancel: "Cancel",
    create: "Create part",
    save: "Save changes",
    close: "Close",
    createSuccess: (name: string) => `${name} was created.`,
    updateSuccess: (name: string) => `${name} was updated.`,
    deleteTitle: "Delete this part?",
    deleteDescription: (name: string) =>
      `You are about to remove ${name}. This action cannot be undone.`,
    bulkDeleteTitle: "Delete selected parts?",
    bulkDeleteDescription: (count: number) =>
      `You are about to remove ${count} selected parts. This action cannot be undone.`,
    confirmDelete: "Delete",
    deleteSuccess: (name: string) => `${name} was deleted.`,
    bulkDeleteSuccess: (count: number) =>
      `${count} selected parts were deleted.`,
    bulkAddTitle: "Add parts in bulk",
    bulkAddDescription: "Create multiple part records for inventory tracking in one go.",
    bulkCreate: "Create parts",
    bulkSuccess: (count: number) => `Successfully created ${count} parts.`,
    addRow: "Add product",
    singleProduct: "Single Product",
    bulkProducts: "Bulk Products",
    keepOneRow: "Please keep at least one product row.",
    rowLabel: "Row",
    removePart: "Remove part",
    validation: {
      partNameRequired: "Enter the part name.",
      partNameLength: "Part name must be at least 2 characters.",
      partNumberRequired: "Enter the part number.",
      quantityRequired: "Enter the quantity.",
      quantityInvalid: "Quantity must be a whole number.",
      priceRequired: "Enter the price.",
      priceInvalid: "Price must be a valid amount.",
      imageInvalid: "File must be a valid image (JPEG, PNG, GIF, WebP).",
      imageSize: "The image must not be larger than 5 MB.",
    },
  },
  sw: {
    addTitle: "Ongeza spea",
    addDescription: "Unda rekodi mpya ya spea kwa ufuatiliaji wa stoo.",
    editTitle: "Hariri spea",
    editDescription: "Sasisha rekodi hii ya spea na taarifa za stoo.",
    viewTitle: "Taarifa za spea",
    viewDescription: "Kagua taarifa za sasa za rekodi ya spea.",
    partName: "Jina la spea",
    partNamePlaceholder: "Weka jina la spea",
    partNumber: "Namba ya spea",
    partNumberPlaceholder: "Weka namba ya spea",
    quantity: "Idadi",
    quantityPlaceholder: "Weka idadi",
    price: "Bei",
    pricePlaceholder: "Weka bei",
    image: "Picha ya spea",
    imageHelper: "Pakia picha ya hiari (JPEG, PNG, GIF, WebP) isiyozidi MB 5.",
    currentImage: "Picha ya sasa",
    category: "Kundi",
    uncategorized: "Haina kundi",
    status: "Hali",
    inStock: "Zipo stoo",
    lowStock: "Stoo ndogo",
    outOfStock: "Hazipo stoo",
    createdAt: "Tarehe ya kuundwa",
    cancel: "Ghairi",
    create: "Ongeza spea",
    save: "Hifadhi mabadiliko",
    close: "Funga",
    createSuccess: (name: string) => `${name} imeongezwa.`,
    updateSuccess: (name: string) => `${name} imesasishwa.`,
    deleteTitle: "Futa spea hii?",
    deleteDescription: (name: string) =>
      `Unakaribia kuondoa ${name}. Hatua hii haiwezi kutenduliwa.`,
    bulkDeleteTitle: "Futa spea zilizochaguliwa?",
    bulkDeleteDescription: (count: number) =>
      `Unakaribia kuondoa spea ${count} zilizochaguliwa. Hatua hii haiwezi kutenduliwa.`,
    confirmDelete: "Futa",
    deleteSuccess: (name: string) => `${name} imefutwa.`,
    bulkDeleteSuccess: (count: number) =>
      `Spea ${count} zilizochaguliwa zimefutwa.`,
    bulkAddTitle: "Ongeza spea kwa pamoja",
    bulkAddDescription: "Sajili spea/bidhaa nyingi kwa mara moja kwenye stoo.",
    bulkCreate: "Sajili spea",
    bulkSuccess: (count: number) => `Imefanikiwa kusajili spea ${count}.`,
    addRow: "Ongeza bidhaa",
    singleProduct: "Bidhaa Moja",
    bulkProducts: "Bidhaa kwa Pamoja",
    keepOneRow: "Tafadhali acha angalau mstari mmoja wa bidhaa.",
    rowLabel: "Mstari",
    removePart: "Ondoa bidhaa",
    validation: {
      partNameRequired: "Weka jina la spea.",
      partNameLength: "Jina la spea liwe na angalau herufi 2.",
      partNumberRequired: "Weka namba ya spea.",
      quantityRequired: "Weka idadi.",
      quantityInvalid: "Idadi lazima iwe namba kamili.",
      priceRequired: "Weka bei.",
      priceInvalid: "Bei lazima iwe kiasi halali.",
      imageInvalid: "Faili lazima iwe picha halali (JPEG, PNG, GIF, WebP).",
      imageSize: "Picha isizidi MB 5.",
    },
  },
} as const satisfies Record<LandingLocale, unknown>

export type ProductDialogCopy = (typeof productDialogCopy)[LandingLocale]
