import type { AppLocale } from "./types"

export const landingContent = {
  en: {
    nav: {
      home: "Home",
      products: "Products",
      contact: "Contact",
      login: "Log in",
      mainNavigation: "Main navigation",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      language: "Choose language",
    },
    hero: {
      eyebrow: "Private inventory workspace",
      title: "Every car part. Accounted for.",
      description:
        "A focused inventory system for Valler Parts owners and authorized workers. Monitor stock, record movements, and catch low-stock items before they slow down the business.",
      login: "Log in to dashboard",
      browse: "View parts",
      access: "Owner-controlled access · No public sign-up",
    },
    products: {
      eyebrow: "Parts overview",
      title: "Know what is on the shelf",
      description:
        "Browse key part categories and move into the dashboard when it is time to update stock.",
      previous: "Previous parts",
      next: "Next parts",
      cards: [
        {
          name: "Engine block",
          category: "Engine components",
          image:
            "/assets/images/Engine_Block_Options_for_Building_Big-Inch_LS_Engines___LS_Engine_DIY-removebg-preview.png",
        },
        {
          name: "Brake caliper",
          category: "Brake system",
          image: "/assets/images/brake_clapper-removebg-preview.png",
        },
        {
          name: "Engine piston",
          category: "Engine components",
          image: "/assets/images/engine_piston-removebg-preview.png",
        },
        {
          name: "Oil filters",
          category: "Service parts",
          image: "/assets/images/filters-removebg-preview.png",
        },
        {
          name: "Suspension spring",
          category: "Suspension",
          image:
            "/assets/images/wheel_spring_for_weight_Support-removebg-preview.png",
        },
      ],
    },
    productsPage: {
      eyebrow: "Parts catalogue",
      title: "A clean view of the parts we manage.",
      description:
        "Explore the main car-part categories handled by Valler Parts. Stock quantities and movements remain protected inside the staff dashboard.",
      note: "Catalogue preview only · Stock data requires staff access",
    },
    contactPage: {
      eyebrow: "Contact and support",
      title: "Reach the Valler Parts team.",
      description:
        "For inventory-system support or company enquiries, use the details below. Staff account access is managed directly by the owner.",
      email: "Email",
      emailValue: "support@vallerparts.co.tz",
      location: "Location",
      locationValue: "Dar es Salaam, Tanzania",
      hours: "Working hours",
      hoursValue: "Monday–Saturday · 8:00 AM–6:00 PM",
      supportTitle: "Need system access?",
      supportDescription:
        "There is no public sign-up. Workers receive their account directly from the owner and can then log in securely.",
      emailAction: "Email support",
      loginAction: "Staff login",
    },
    authLogin: {
      homeAriaLabel: "Go home",
      title: "Private Sign In",
      description: "Welcome back! Sign in to continue",
      emailLabel: "Email Address",
      emailPlaceholder: "Enter your email address",
      emailHelper: "Use the email linked to your account access.",
      passwordLabel: "Password",
      passwordPlaceholder: "Enter your password",
      passwordRules: [
        "Minimum 6 characters.",
        "Include at least one uppercase letter.",
        "Include at least one number or special character.",
      ],
      forgotPassword: "Forgot Password?",
      submit: "Sign In",
      alternativeDivider: "Or continue with",
      returnHomePrompt: "Want to return home?",
      returnHomeAction: "Back home",
    },
    dashboardUsers: {
      you: "You",
      searchPlaceholder: "Search users...",
      loading: "Loading users from the server.",
      loadErrorTitle: "Unable to load users",
      retry: "Try again",
      bulkDelete: "Delete selected",
      showing: "Showing",
      sort: "Sort",
      ascending: "Asc",
      descending: "Desc",
      status: "Status",
      allStatuses: "All",
      active: "Active",
      inactive: "Inactive",
      selectAll: "Select all users on this page",
      selectUser: "Select user",
      number: "#",
      fullName: "Full name",
      email: "Email",
      phone: "Phone",
      role: "Role",
      createdAt: "Created at",
      actions: "Actions",
      of: "of",
      previous: "Previous",
      next: "Next",
      previousPage: "Go to previous page",
      nextPage: "Go to next page",
      openActions: "Open actions for",
      viewUser: "View user",
      editUser: "Edit user",
      deleteUser: "Delete user",
      emptyTitle: "No users yet",
      emptyDescription:
        "Add a user to start managing access to this workspace.",
      noResultsTitle: "No matching users",
      noResultsDescription: "Try changing your search or filter selection.",
      addUser: "Add user",
    },
    dashboardCategories: {
      searchPlaceholder: "Search categories...",
      loading: "Loading categories from the server.",
      loadErrorTitle: "Unable to load categories",
      retry: "Try again",
      bulkDelete: "Delete selected",
      showing: "Showing",
      sort: "Sort",
      ascending: "Asc",
      descending: "Desc",
      selectAll: "Select all categories on this page",
      selectCategory: "Select category",
      number: "#",
      name: "Category name",
      createdAt: "Created at",
      actions: "Actions",
      of: "of",
      previous: "Previous",
      next: "Next",
      previousPage: "Go to previous page",
      nextPage: "Go to next page",
      openActions: "Open actions for",
      viewCategory: "View category",
      editCategory: "Edit category",
      deleteCategory: "Delete category",
      emptyTitle: "No categories yet",
      emptyDescription:
        "Add a category to keep products and parts organized.",
      noResultsTitle: "No matching categories",
      noResultsDescription: "Try changing your search term.",
      addCategory: "Add category",
    },
    dashboardProducts: {
      searchPlaceholder: "Search parts...",
      loading: "Loading parts from the server.",
      loadErrorTitle: "Unable to load parts",
      retry: "Try again",
      bulkDelete: "Delete selected",
      showing: "Showing",
      sort: "Sort",
      ascending: "Asc",
      descending: "Desc",
      status: "Status",
      allStatuses: "All",
      inStock: "In stock",
      lowStock: "Low stock",
      outOfStock: "Out of stock",
      uncategorized: "Uncategorized",
      selectAll: "Select all parts on this page",
      selectPart: "Select part",
      number: "#",
      partName: "Part name",
      partNumber: "Part number",
      category: "Category",
      quantity: "Quantity",
      price: "Price",
      createdAt: "Created at",
      actions: "Actions",
      of: "of",
      previous: "Previous",
      next: "Next",
      previousPage: "Go to previous page",
      nextPage: "Go to next page",
      openActions: "Open actions for",
      viewPart: "View part",
      editPart: "Edit part",
      deletePart: "Delete part",
      emptyTitle: "No parts yet",
      emptyDescription:
        "Add a part to start tracking inventory records.",
      noResultsTitle: "No matching parts",
      noResultsDescription: "Try changing your search or filter selection.",
      addPart: "Add part",
      totalParts: "Total parts (By quantity)",
    },
    footer: {
      description:
        "Private stock control for the Valler Parts team. Built to keep every movement clear and every shelf accountable.",
      navigation: "Navigation",
      system: "System",
      access: "Secure access",
      accessDescription:
        "Workers are registered by the owner. Public account creation is disabled.",
      contact: "Contact",
      emailLabel: "Inventory support",
      rights: "All rights reserved.",
    },
  },
  sw: {
    nav: {
      home: "Nyumbani",
      products: "Bidhaa",
      contact: "Mawasiliano",
      login: "Ingia",
      mainNavigation: "Menyu kuu",
      openMenu: "Fungua menyu",
      closeMenu: "Funga menyu",
      language: "Chagua lugha",
    },
    hero: {
      eyebrow: "Mfumo binafsi wa usimamizi wa stoo",
      title: "Kila spea ya gari. Imehesabiwa.",
      description:
        "Mfumo rahisi wa stoo kwa mmiliki wa Valler Parts na wafanyakazi walioidhinishwa. Fuatilia bidhaa, rekodi mzunguko wa spea, na tambua bidhaa zinazokaribia kuisha mapema.",
      login: "Ingia kwenye dashibodi",
      browse: "Tazama spea",
      access: "Ufikiaji unasimamiwa na mmiliki · Hakuna kujisajili hadharani",
    },
    products: {
      eyebrow: "Muhtasari wa spea",
      title: "Jua kilichopo kwenye stoo",
      description:
        "Tazama aina muhimu za spea na uingie kwenye dashibodi unapohitaji kusasisha stoo.",
      previous: "Spea zilizotangulia",
      next: "Spea zinazofuata",
      cards: [
        {
          name: "Bloku ya injini",
          category: "Vipuri vya injini",
          image:
            "/assets/images/Engine_Block_Options_for_Building_Big-Inch_LS_Engines___LS_Engine_DIY-removebg-preview.png",
        },
        {
          name: "Kalipa ya breki",
          category: "Mfumo wa breki",
          image: "/assets/images/brake_clapper-removebg-preview.png",
        },
        {
          name: "Pistoni ya injini",
          category: "Vipuri vya injini",
          image: "/assets/images/engine_piston-removebg-preview.png",
        },
        {
          name: "Vichujio vya mafuta",
          category: "Vipuri vya huduma",
          image: "/assets/images/filters-removebg-preview.png",
        },
        {
          name: "Springi ya suspension",
          category: "Mfumo wa suspension",
          image:
            "/assets/images/wheel_spring_for_weight_Support-removebg-preview.png",
        },
      ],
    },
    productsPage: {
      eyebrow: "Orodha ya spea",
      title: "Muonekano safi wa spea tunazosimamia.",
      description:
        "Tazama aina kuu za spea zinazoshughulikiwa na Valler Parts. Idadi na mzunguko wa stoo hubaki salama ndani ya dashibodi ya wafanyakazi.",
      note: "Muhtasari wa bidhaa pekee · Taarifa za stoo zinahitaji ruhusa ya mfanyakazi",
    },
    contactPage: {
      eyebrow: "Mawasiliano na msaada",
      title: "Wasiliana na timu ya Valler Parts.",
      description:
        "Kwa msaada wa mfumo wa stoo au mawasiliano ya kampuni, tumia taarifa zilizo hapa chini. Ufikiaji wa wafanyakazi unasimamiwa moja kwa moja na mmiliki.",
      email: "Barua pepe",
      emailValue: "support@vallerparts.co.tz",
      location: "Mahali",
      locationValue: "Dar es Salaam, Tanzania",
      hours: "Saa za kazi",
      hoursValue: "Jumatatu–Jumamosi · 8:00 asubuhi–6:00 jioni",
      supportTitle: "Unahitaji kuingia kwenye mfumo?",
      supportDescription:
        "Hakuna kujisajili hadharani. Wafanyakazi hupokea akaunti moja kwa moja kutoka kwa mmiliki kisha huingia kwa usalama.",
      emailAction: "Tuma barua pepe",
      loginAction: "Ingia kama mfanyakazi",
    },
    authLogin: {
      homeAriaLabel: "Rudi nyumbani",
      title: "Ingia Kwenye Mfumo",
      description: "Karibu tena! Ingia ili kuendelea",
      emailLabel: "Anwani ya barua pepe",
      emailPlaceholder: "Weka anwani yako ya barua pepe",
      emailHelper:
        "Tumia barua pepe iliyounganishwa na ruhusa ya akaunti yako.",
      passwordLabel: "Nenosiri",
      passwordPlaceholder: "Weka nenosiri lako",
      passwordRules: [
        "Angalau herufi 6.",
        "Jumuisha angalau herufi moja kubwa.",
        "Jumuisha angalau namba moja au alama maalum.",
      ],
      forgotPassword: "Umesahau nenosiri?",
      submit: "Ingia",
      alternativeDivider: "Au endelea na",
      returnHomePrompt: "Unataka kurudi nyumbani?",
      returnHomeAction: "Rudi nyumbani",
    },
    dashboardUsers: {
      you: "Wewe",
      searchPlaceholder: "Tafuta watumiaji...",
      loading: "Watumiaji wanapakiwa kutoka kwenye seva.",
      loadErrorTitle: "Imeshindikana kupakia watumiaji",
      retry: "Jaribu tena",
      bulkDelete: "Futa waliochaguliwa",
      showing: "Onyesha",
      sort: "Panga",
      ascending: "Kupanda",
      descending: "Kushuka",
      status: "Hali",
      allStatuses: "Hali zote",
      active: "Hai",
      inactive: "Si Hai",
      selectAll: "Chagua watumiaji wote kwenye ukurasa huu",
      selectUser: "Chagua mtumiaji",
      number: "#",
      fullName: "Jina kamili",
      email: "Barua pepe",
      phone: "Simu",
      role: "Wajibu",
      createdAt: "Tarehe ya kuundwa",
      actions: "Vitendo",
      of: "kati ya",
      previous: "Nyuma",
      next: "Mbele",
      previousPage: "Nenda ukurasa uliopita",
      nextPage: "Nenda ukurasa unaofuata",
      openActions: "Fungua vitendo vya",
      viewUser: "Angalia mtumiaji",
      editUser: "Hariri mtumiaji",
      deleteUser: "Futa mtumiaji",
      emptyTitle: "Hakuna watumiaji bado",
      emptyDescription:
        "Ongeza mtumiaji ili kuanza kusimamia ruhusa za eneo hili.",
      noResultsTitle: "Hakuna watumiaji waliopatikana",
      noResultsDescription: "Badilisha utafutaji au kichujio chako.",
      addUser: "Ongeza mtumiaji",
    },
    dashboardCategories: {
      searchPlaceholder: "Tafuta makundi...",
      loading: "Makundi yanapakiwa kutoka kwenye seva.",
      loadErrorTitle: "Imeshindikana kupakia makundi",
      retry: "Jaribu tena",
      bulkDelete: "Futa yaliyochaguliwa",
      showing: "Onyesha",
      sort: "Panga",
      ascending: "Kupanda",
      descending: "Kushuka",
      selectAll: "Chagua makundi yote kwenye ukurasa huu",
      selectCategory: "Chagua kundi",
      number: "#",
      name: "Jina la kundi",
      createdAt: "Tarehe ya kuundwa",
      actions: "Vitendo",
      of: "kati ya",
      previous: "Nyuma",
      next: "Mbele",
      previousPage: "Nenda ukurasa uliopita",
      nextPage: "Nenda ukurasa unaofuata",
      openActions: "Fungua vitendo vya",
      viewCategory: "Angalia kundi",
      editCategory: "Hariri kundi",
      deleteCategory: "Futa kundi",
      emptyTitle: "Hakuna makundi bado",
      emptyDescription:
        "Ongeza kundi ili kupanga bidhaa na spea vizuri.",
      noResultsTitle: "Hakuna makundi yaliyopatikana",
      noResultsDescription: "Badilisha neno la utafutaji.",
      addCategory: "Ongeza kundi",
    },
    dashboardProducts: {
      searchPlaceholder: "Tafuta spea...",
      loading: "Spea zinapakiwa kutoka kwenye seva.",
      loadErrorTitle: "Imeshindikana kupakia spea",
      retry: "Jaribu tena",
      bulkDelete: "Futa zilizochaguliwa",
      showing: "Onyesha",
      sort: "Panga",
      ascending: "Kupanda",
      descending: "Kushuka",
      status: "Hali",
      allStatuses: "Hali zote",
      inStock: "Zilizopo stoo",
      lowStock: "Zilizo chache",
      outOfStock: "Zilizoisha stoo",
      uncategorized: "Haina kundi",
      selectAll: "Chagua spea zote kwenye ukurasa huu",
      selectPart: "Chagua spea",
      number: "#",
      partName: "Jina la spea",
      partNumber: "Namba ya spea",
      category: "Kundi",
      quantity: "Idadi",
      price: "Bei",
      createdAt: "Tarehe ya kuundwa",
      actions: "Vitendo",
      of: "kati ya",
      previous: "Nyuma",
      next: "Mbele",
      previousPage: "Nenda ukurasa uliopita",
      nextPage: "Nenda ukurasa unaofuata",
      openActions: "Fungua vitendo vya",
      viewPart: "Angalia spea",
      editPart: "Hariri spea",
      deletePart: "Futa spea",
      emptyTitle: "Hakuna spea bado",
      emptyDescription:
        "Ongeza spea ili kuanza kufuatilia stoo.",
      noResultsTitle: "Hakuna spea zilizopatikana",
      noResultsDescription: "Badilisha utafutaji au kichujio chako.",
      addPart: "Ongeza spea",
      totalParts: "Jumla ya Spea (Kwa idadi)",
    },
    footer: {
      description:
        "Usimamizi binafsi wa stoo kwa timu ya Valler Parts. Umeundwa kuweka kila mzunguko wazi na kila bidhaa ikihesabika.",
      navigation: "Menyu",
      system: "Mfumo",
      access: "Ufikiaji salama",
      accessDescription:
        "Wafanyakazi husajiliwa na mmiliki. Utengenezaji wa akaunti hadharani umezimwa.",
      contact: "Mawasiliano",
      emailLabel: "Msaada wa mfumo wa stoo",
      rights: "Haki zote zimehifadhiwa.",
    },
  },
} as const

export type LandingLocale = AppLocale
