import type { LandingLocale } from "@/lib/landing-content"

import type { LocalizedDebtCopy } from "../../components/debt-feature-types"

export const payableDialogCopy = {
  en: {
    addTitle: "Add payable debt",
    addBtn: "Add Payable",
    addDescription:
      "Record an amount the business owes a person or organization.",
    searchPlaceholder: "Search payable debts...",
    showing: "Showing",
    sort: "Sort",
    ascending: "Ascending",
    descending: "Descending",
    loadingTitle: "Loading payables...",
    loadingDescription: "Payable debt records are loading from the server.",
    loadErrorTitle: "Unable to load payables",
    emptyTitle: "No payables yet",
    emptyDescription:
      "Debt-marked stock intakes and manually recorded debts will appear here.",
    noResultsTitle: "No matching payables",
    noResultsDescription: "Try changing your search term or due-date filter.",
    statsPaid: "Paid",
    statsNotPaid: "Not paid",
    statsDue: "Due",
    statsDueWithin: "Due soon",
    dueFilter: "Due filter",
    allDueDates: "All due dates",
    dueNow: "Due / overdue",
    within1Day: "1 day left",
    within3Days: "3 days left",
    within7Days: "7 days left",
    within31Days: "31 days left",
    within186Days: "6 months left",
    within366Days: "1 year left",
    viewTitle: "Payable details",
    viewDescription: "Creditor balance, payment, and source details.",
    partyName: "Creditor name",
    partyNamePlaceholder: "Enter the person or organization owed",
    partyPhone: "Creditor phone",
    partyPhonePlaceholder: "Enter creditor phone (optional)",
    referenceNumber: "Reference number",
    referenceNumberPlaceholder: "Invoice or other reference (optional)",
    totalAmount: "Total payable",
    amountPaid: "Amount paid",
    balanceAmount: "Balance payable",
    status: "Payment status",
    debtDate: "Debt date",
    debtDateTodayToggle: "Debt date is today",
    debtDateTodayDescription:
      "Keep this checked to use today's date, or uncheck it to select another debt start date.",
    dueDate: "Debt end date",
    source: "Stock intake",
    manualEntry: "Manual entry",
    notes: "Notes",
    notesPlaceholder: "Add payment terms or follow-up notes",
    createdBy: "Recorded by",
    createdAt: "Created at",
    statusPending: "Pending",
    statusPartial: "Partially paid",
    statusPaid: "Paid",
    cancel: "Cancel",
    create: "Save Payable",
    close: "Close",
    actions: "Actions",
    openActions: "Open payable actions",
    createSuccess: "Payable record was created.",
    deleteTitle: "Delete payable record?",
    deleteDescription:
      "This removes the debt record but does not delete its stock intake.",
    confirmDelete: "Delete",
    deleteSuccess: "Payable record was deleted.",
    deleteError: "Failed to delete payable record.",
    validation: {
      partyRequired: "Enter the creditor name.",
      totalRequired: "Total payable must be greater than 0.",
      amountPaidInvalid: "Amount paid must be between 0 and the total payable.",
      debtDateRequired: "Select the debt date.",
      dueDateBeforeDebtDate: "Due date cannot be earlier than the debt date.",
    },
  },
  sw: {
    addTitle: "Ongeza deni la kulipa",
    addBtn: "Ongeza Deni la Kulipa",
    addDescription: "Rekodi kiasi ambacho biashara inadaiwa na mtu au taasisi.",
    searchPlaceholder: "Tafuta madeni ya kulipa...",
    showing: "Onyesha",
    sort: "Panga",
    ascending: "Kupanda",
    descending: "Kushuka",
    loadingTitle: "Madeni ya kulipa yanapakiwa...",
    loadingDescription:
      "Rekodi za madeni ya kulipa zinapakiwa kutoka kwenye seva.",
    loadErrorTitle: "Imeshindikana kupakia madeni ya kulipa",
    emptyTitle: "Hakuna madeni ya kulipa bado",
    emptyDescription:
      "Uingizaji wa stoo wa deni na madeni yaliyowekwa moja kwa moja yataonekana hapa.",
    noResultsTitle: "Hakuna deni linalolingana",
    noResultsDescription:
      "Jaribu kubadilisha utafutaji au kichujio cha tarehe.",
    statsPaid: "Yaliyolipwa",
    statsNotPaid: "Hayajalipwa",
    statsDue: "Yamefika muda",
    statsDueWithin: "Yanayokaribia",
    dueFilter: "Chuja kwa muda",
    allDueDates: "Tarehe zote",
    dueNow: "Yamefika / yamechelewa",
    within1Day: "Imebaki siku 1",
    within3Days: "Zimebaki siku 3",
    within7Days: "Zimebaki siku 7",
    within31Days: "Zimebaki siku 31",
    within186Days: "Imebaki miezi 6",
    within366Days: "Umebaki mwaka 1",
    viewTitle: "Maelezo ya deni la kulipa",
    viewDescription: "Salio la mdai, malipo, na chanzo cha deni.",
    partyName: "Jina la mdai",
    partyNamePlaceholder: "Weka mtu au taasisi inayodai",
    partyPhone: "Simu ya mdai",
    partyPhonePlaceholder: "Weka simu ya mdai (si lazima)",
    referenceNumber: "Namba ya rejea",
    referenceNumberPlaceholder: "Ankara au rejea nyingine (si lazima)",
    totalAmount: "Jumla ya deni",
    amountPaid: "Kiasi kilicholipwa",
    balanceAmount: "Salio la kulipa",
    status: "Hali ya malipo",
    debtDate: "Tarehe ya deni",
    debtDateTodayToggle: "Tarehe ya deni ni leo",
    debtDateTodayDescription:
      "Acha tiki ili kutumia tarehe ya leo, au ondoa tiki kuchagua tarehe nyingine ya kuanza kwa deni.",
    dueDate: "Tarehe ya mwisho ya deni",
    source: "Uingizaji wa stoo",
    manualEntry: "Imewekwa moja kwa moja",
    notes: "Maelezo ya ziada",
    notesPlaceholder: "Weka masharti ya malipo au maelezo ya ufuatiliaji",
    createdBy: "Imerekodiwa na",
    createdAt: "Tarehe ya kuundwa",
    statusPending: "Inasubiri",
    statusPartial: "Imelipwa sehemu",
    statusPaid: "Imelipwa",
    cancel: "Ghairi",
    create: "Hifadhi Deni",
    close: "Funga",
    actions: "Vitendo",
    openActions: "Fungua vitendo vya deni la kulipa",
    createSuccess: "Deni la kulipa limeundwa.",
    deleteTitle: "Futa deni hili la kulipa?",
    deleteDescription:
      "Hatua hii itaondoa deni bila kufuta rekodi ya uingizaji wa stoo.",
    confirmDelete: "Futa",
    deleteSuccess: "Deni la kulipa limefutwa.",
    deleteError: "Imeshindikana kufuta deni la kulipa.",
    validation: {
      partyRequired: "Weka jina la mdai.",
      totalRequired: "Jumla ya deni lazima iwe zaidi ya 0.",
      amountPaidInvalid:
        "Kiasi kilicholipwa lazima kiwe kati ya 0 na jumla ya deni.",
      debtDateRequired: "Chagua tarehe ya deni.",
      dueDateBeforeDebtDate:
        "Tarehe ya mwisho haiwezi kuwa kabla ya tarehe ya deni.",
    },
  },
} as const satisfies LocalizedDebtCopy

export type PayableDialogCopy = (typeof payableDialogCopy)[LandingLocale]
