import type { LandingLocale } from "@/lib/landing-content"

export const salesDialogCopy = {
  en: {
    addTitle: "Register counter sale",
    addBtn: "Add Sale",
    addDescription: "Record cash/mobile counter sale transaction and update stock.",
    searchPlaceholder: "Search sales...",
    showing: "Showing",
    sort: "Sort",
    ascending: "Ascending",
    descending: "Descending",
    loadingTitle: "Loading sales...",
    loadingDescription: "Sale records are loading from the server.",
    loadErrorTitle: "Unable to load sales",
    emptyTitle: "No sales yet",
    emptyDescription: "Register the first counter sale to start tracking sales.",
    noResultsTitle: "No matching sales",
    noResultsDescription: "Try changing your search term.",
    viewTitle: "Sale details",
    viewDescription: "Receipt and details of this sale.",
    saleNumber: "Sale number",
    saleNumberPlaceholder: "Enter sale reference (optional)",
    customerName: "Customer Name",
    customerPlaceholder: "Enter customer name",
    customerPhone: "Customer Phone",
    customerPhonePlaceholder: "Enter customer phone",
    debtToggle: "This sale is a debt",
    debtDescription: "Collect customer and payment details and create a receivable for the unpaid balance.",
    debtDueDate: "Debt due date",
    debtAmountPaid: "Amount already paid",
    paymentStatus: "Payment Status",
    paymentMethod: "Payment Method",
    amountPaid: "Amount Paid",
    totalAmount: "Total Amount",
    productTotal: "Products Total",
    additionalAmount: "Additional Amount",
    additionalAmountPlaceholder: "Enter additional amount",
    additionalAmountToggle: "Include additional amount",
    additionalAmountDescription: "Use this only when the customer paid an extra charge outside the selected products.",
    grandTotal: "Grand Total",
    grandTotalFormula: "Total products + Additional Price",
    notes: "Notes",
    notesPlaceholder: "Add any extra details or notes",
    loggedBy: "Sold by",
    soldAt: "Sale date & time",
    createdAt: "Created at",
    cancel: "Cancel",
    create: "Complete Sale",
    close: "Close",
    createSuccess: "Sale transaction registered successfully.",
    deleteTitle: "Delete sale record?",
    deleteDescription: "Are you sure you want to delete this sale? This will restore the stock quantities.",
    confirmDelete: "Delete",
    deleteSuccess: "Sale record was deleted.",
    partSearchPlaceholder: "Search part...",
    qtyLabel: "Qty",
    priceLabel: "Price",
    subtotalLabel: "Subtotal",
    addRowBtn: "Add part",
    partNameLabel: "Part Name",
    partNumberLabel: "No",
    skuLabel: "SKU",
    available: "Available",
    currentStock: "Current Stock",
    walkInCustomer: "Walk-in Customer",
    totalItemsSoldByQuantity: "Total items sold (By Quantity)",
    actions: "Actions",
    openActions: "Open sale actions",
    removePart: "Remove part",
    emptyPartsWarning: "Please add at least one part item to register a sale.",
    insufficientStock: "Insufficient stock for",
    deleteError: "Failed to delete sale record.",
    validation: {
      soldAtRequired: "Select the sale date.",
      partRequired: "Select a part.",
      qtyRequired: "Quantity must be at least 1.",
      priceRequired: "Price must be at least 0.",
      paymentStatusRequired: "Select payment status.",
      paymentMethodRequired: "Select payment method.",
      debtCustomerRequired: "Enter the customer's name for a debt sale.",
      debtPhoneRequired: "Enter the customer's phone number for a debt sale.",
      debtAmountInvalid: "Amount already paid must be at least 0 and less than the grand total.",
    },
    changeBtn: "Change",
    statusPaid: "Paid",
    statusPending: "Pending",
    statusPartial: "Partial",
    methodCash: "Cash",
    methodMobileMoney: "Mobile Money",
    methodBankTransfer: "Bank Transfer",
  },
  sw: {
    addTitle: "Sajili mauzo ya kaunta",
    addBtn: "Ongeza Mauzo",
    addDescription: "Rekodi shughuli ya mauzo ya kaunta na usasishe idadi ya stoo.",
    searchPlaceholder: "Tafuta mauzo...",
    showing: "Onyesha",
    sort: "Panga",
    ascending: "Kupanda",
    descending: "Kushuka",
    loadingTitle: "Rekodi za mauzo zinapakiwa...",
    loadingDescription: "Rekodi za mauzo zinapakiwa kutoka kwenye seva.",
    loadErrorTitle: "Imeshindikana kupakia rekodi za mauzo",
    emptyTitle: "Hakuna mauzo bado",
    emptyDescription: "Sajili mauzo ya kwanza ya kaunta ili kuanza kufuatilia mauzo.",
    noResultsTitle: "Hakuna mauzo yaliyopatikana",
    noResultsDescription: "Jaribu kubadilisha neno la utafutaji.",
    viewTitle: "Maelezo ya mauzo",
    viewDescription: "Stakabadhi na maelezo ya mauzo haya.",
    saleNumber: "Namba ya mauzo",
    saleNumberPlaceholder: "Weka namba ya rejea ya mauzo (si lazima)",
    customerName: "Jina la Mteja",
    customerPlaceholder: "Weka jina la mteja",
    customerPhone: "Simu ya Mteja",
    customerPhonePlaceholder: "Weka namba ya simu ya mteja",
    debtToggle: "Mauzo haya ni ya deni",
    debtDescription: "Kusanya maelezo ya mteja na malipo, kisha unda deni kwa salio ambalo halijalipwa.",
    debtDueDate: "Tarehe ya mwisho ya deni",
    debtAmountPaid: "Kiasi kilicholipwa tayari",
    paymentStatus: "Hali ya Malipo",
    paymentMethod: "Njia ya Malipo",
    amountPaid: "Kiasi Kilicholipwa",
    totalAmount: "Jumla ya Kiasi",
    productTotal: "Jumla ya Bidhaa",
    additionalAmount: "Kiasi cha Ziada",
    additionalAmountPlaceholder: "Weka kiasi cha ziada",
    additionalAmountToggle: "Jumuisha kiasi cha ziada",
    additionalAmountDescription: "Tumia hii tu kama mteja amelipa gharama ya ziada nje ya bidhaa zilizochaguliwa.",
    grandTotal: "Jumla Kuu",
    grandTotalFormula: "Jumla ya bidhaa + Bei ya ziada",
    notes: "Maelezo ya ziada",
    notesPlaceholder: "Weka maelezo yoyote ya ziada",
    loggedBy: "Muuza bidhaa",
    soldAt: "Tarehe na muda wa mauzo",
    createdAt: "Tarehe ya kuundwa",
    cancel: "Ghairi",
    create: "Kamilisha Mauzo",
    close: "Funga",
    createSuccess: "Shughuli ya mauzo imesajiliwa kikamilifu.",
    deleteTitle: "Futa rekodi hii?",
    deleteDescription: "Una uhakika unataka kufuta mauzo haya? Hatua hii itarejesha idadi ya stoo iliyouzwa.",
    confirmDelete: "Futa",
    deleteSuccess: "Rekodi ya mauzo imefutwa.",
    partSearchPlaceholder: "Tafuta spea/bidhaa...",
    qtyLabel: "Kiasi",
    priceLabel: "Bei",
    subtotalLabel: "Jumla ndogo",
    addRowBtn: "Ongeza bidhaa",
    partNameLabel: "Jina la Bidhaa",
    partNumberLabel: "Namba",
    skuLabel: "SKU",
    available: "Iliyopo",
    currentStock: "Stoo ya Sasa",
    walkInCustomer: "Mteja wa Dukani",
    totalItemsSoldByQuantity: "Jumla ya bidhaa zilizouzwa (Kwa Idadi)",
    actions: "Vitendo",
    openActions: "Fungua vitendo vya mauzo",
    removePart: "Ondoa bidhaa",
    emptyPartsWarning: "Tafadhali ongeza angalau bidhaa moja ili kusajili.",
    insufficientStock: "Stoo haitoshi kwa",
    deleteError: "Imeshindikana kufuta rekodi ya mauzo.",
    validation: {
      soldAtRequired: "Chagua tarehe ya mauzo.",
      partRequired: "Chagua spea/bidhaa.",
      qtyRequired: "Kiasi lazima kiwe angalau 1.",
      priceRequired: "Bei lazima iwe angalau 0.",
      paymentStatusRequired: "Chagua hali ya malipo.",
      paymentMethodRequired: "Chagua njia ya malipo.",
      debtCustomerRequired: "Weka jina la mteja kwa mauzo ya deni.",
      debtPhoneRequired: "Weka namba ya simu ya mteja kwa mauzo ya deni.",
      debtAmountInvalid: "Kiasi kilicholipwa lazima kiwe kuanzia 0 na chini ya jumla kuu.",
    },
    changeBtn: "Badilisha",
    statusPaid: "Imelipwa",
    statusPending: "Inasubiri",
    statusPartial: "Sehemu",
    methodCash: "Taslimu",
    methodMobileMoney: "Pesa ya Simu",
    methodBankTransfer: "Uhamisho wa Benki",
  },
} as const satisfies Record<LandingLocale, unknown>

export type SalesDialogCopy = (typeof salesDialogCopy)[LandingLocale]
