import type { LandingLocale } from "@/lib/landing-content"

export const salesDialogCopy = {
  en: {
    addTitle: "Register counter sale",
    addBtn: "Add Sale",
    addDescription: "Record cash/mobile counter sale transaction and update stock.",
    viewTitle: "Sale details",
    viewDescription: "Receipt and details of this sale.",
    saleNumber: "Sale number",
    saleNumberPlaceholder: "Enter sale reference (optional)",
    customerName: "Customer Name",
    customerPlaceholder: "Enter customer name",
    paymentStatus: "Payment Status",
    paymentMethod: "Payment Method",
    amountPaid: "Amount Paid",
    notes: "Notes",
    notesPlaceholder: "Add any extra details or notes",
    loggedBy: "Sold by",
    soldAt: "Sale date & time",
    createdAt: "Created at",
    cancel: "Cancel",
    create: "Complete Sale",
    close: "Close",
    createSuccess: "Sale transaction registered successfully.",
    deleteTitle: "Delete sale record?",
    deleteDescription: "Are you sure you want to delete this sale? This will restore the stock quantities.",
    confirmDelete: "Delete",
    deleteSuccess: "Sale record was deleted.",
    partSearchPlaceholder: "Search part...",
    qtyLabel: "Qty",
    priceLabel: "Price",
    subtotalLabel: "Subtotal",
    addRowBtn: "Add part",
    emptyPartsWarning: "Please add at least one part item to register a sale.",
    validation: {
      soldAtRequired: "Select the sale date.",
      partRequired: "Select a part.",
      qtyRequired: "Quantity must be at least 1.",
      priceRequired: "Price must be at least 0.",
      paymentStatusRequired: "Select payment status.",
      paymentMethodRequired: "Select payment method.",
    },
    changeBtn: "Change",
    statusPaid: "Paid",
    statusPending: "Pending",
    statusPartial: "Partial",
    methodCash: "Cash",
    methodMobileMoney: "Mobile Money",
    methodBankTransfer: "Bank Transfer",
  },
  sw: {
    addTitle: "Sajili mauzo ya kaunta",
    addBtn: "Ongeza Mauzo",
    addDescription: "Rekodi shughuli ya mauzo ya kaunta na usasishe idadi ya stoo.",
    viewTitle: "Maelezo ya mauzo",
    viewDescription: "Stakabadhi na maelezo ya mauzo haya.",
    saleNumber: "Namba ya mauzo",
    saleNumberPlaceholder: "Weka namba ya rejea ya mauzo (si lazima)",
    customerName: "Jina la Mteja",
    customerPlaceholder: "Weka jina la mteja",
    paymentStatus: "Hali ya Malipo",
    paymentMethod: "Njia ya Malipo",
    amountPaid: "Kiasi Kilicholipwa",
    notes: "Maelezo ya ziada",
    notesPlaceholder: "Weka maelezo yoyote ya ziada",
    loggedBy: "Muuza bidhaa",
    soldAt: "Tarehe na muda wa mauzo",
    createdAt: "Tarehe ya kuundwa",
    cancel: "Ghairi",
    create: "Kamilisha Mauzo",
    close: "Funga",
    createSuccess: "Shughuli ya mauzo imesajiliwa kikamilifu.",
    deleteTitle: "Futa rekodi hii?",
    deleteDescription: "Una uhakika unataka kufuta mauzo haya? Hatua hii itarejesha idadi ya stoo iliyouzwa.",
    confirmDelete: "Futa",
    deleteSuccess: "Rekodi ya mauzo imefutwa.",
    partSearchPlaceholder: "Tafuta spea/bidhaa...",
    qtyLabel: "Kiasi",
    priceLabel: "Bei",
    subtotalLabel: "Jumla ndogo",
    addRowBtn: "Ongeza bidhaa",
    emptyPartsWarning: "Tafadhali ongeza angalau bidhaa moja ili kusajili.",
    validation: {
      soldAtRequired: "Chagua tarehe ya mauzo.",
      partRequired: "Chagua spea/bidhaa.",
      qtyRequired: "Kiasi lazima kiwe angalau 1.",
      priceRequired: "Bei lazima iwe angalau 0.",
      paymentStatusRequired: "Chagua hali ya malipo.",
      paymentMethodRequired: "Chagua njia ya malipo.",
    },
    changeBtn: "Badilisha",
    statusPaid: "Imelipwa",
    statusPending: "Inasubiri",
    statusPartial: "Sehemu",
    methodCash: "Taslimu",
    methodMobileMoney: "Pesa ya Simu",
    methodBankTransfer: "Uhamisho wa Benki",
  },
} as const satisfies Record<LandingLocale, unknown>

export type SalesDialogCopy = (typeof salesDialogCopy)[LandingLocale]
