import type { LandingLocale } from "@/lib/landing-content"
import { defineLocalizedCopy, type LocalizedCopy } from "@/lib/localized-copy"

export const settingsCopy = defineLocalizedCopy({
  en: {
    groups: { account: "Account", workspace: "Workspace" },
    tabs: {
      profile: "Profile",
      general: "General",
      notifications: "Notifications",
      inventory: "Inventory",
    },
    loading: "Loading settings",
    saved: "Saved",
    saveFailed: "Could not save this setting.",
    profile: {
      detailsTitle: "Profile details",
      detailsDescription: "Update your personal and contact information.",
      firstName: "First name",
      lastName: "Last name",
      email: "Email address",
      phone: "Phone number",
      save: "Save details",
      saved: "Profile updated.",
      loadFailed: "Could not load your profile.",
      passwordTitle: "Change password",
      passwordDescription: "Use a strong password you do not use elsewhere.",
      oldPassword: "Old password",
      newPassword: "New password",
      confirmPassword: "Confirm password",
      changePassword: "Change password",
      passwordConfirmTitle: "Change your password?",
      passwordConfirmDescription:
        "Your current sessions will end and you will need to sign in again.",
      confirmChangePassword: "Confirm change",
      passwordChanged: "Password changed. Sign in again.",
      dangerTitle: "Danger zone",
      dangerDescription:
        "Permanently delete this account and revoke its access.",
      deleteAccount: "Delete account",
      deleteBlocked: "Add another administrator before deleting this account.",
      deleteDialogTitle: "Delete your account?",
      deleteDialogDescription:
        "This cannot be undone. Enter your current password to continue.",
      confirmDelete: "Delete permanently",
      cancel: "Cancel",
      logoutTitle: "Sign out",
      logoutDescription: "End this session on the current device.",
      logout: "Sign out",
      logoutConfirmTitle: "Sign out now?",
      logoutConfirmDescription: "You will need to enter your password again.",
      retry: "Retry",
      validation: {
        firstName: "Enter at least 2 characters.",
        lastName: "Enter at least 2 characters.",
        email: "Enter a valid email address.",
        phone: "Enter a valid phone number.",
        oldPassword: "Enter your old password.",
        newPassword: "Use 8+ characters, an uppercase letter, and a number.",
        samePassword: "Choose a password different from the old password.",
        confirmPassword: "The passwords do not match.",
        deletePassword: "Enter your current password.",
      },
    },
    general: {
      appearance: "Appearance",
      appearanceDescription: "Choose how the dashboard looks on this device.",
      light: "Light",
      dark: "Dark",
      system: "System",
      language: "Language",
      languageDescription: "Choose the language used across the dashboard.",
      english: "English",
      swahili: "Kiswahili",
      compactTables: "Compact tables",
      compactTablesDescription: "Use tighter spacing in data tables.",
    },
    notifications: {
      lowStock: "Low-stock alerts",
      lowStockDescription: "Notify when stock reaches its threshold.",
      sales: "Daily sales summary",
      salesDescription: "Receive a daily sales summary.",
      debt: "Debt reminders",
      debtDescription: "Remind me about balances needing attention.",
    },
    inventory: {
      threshold: "Low-stock threshold",
      thresholdDescription: "Default threshold for new products.",
      items: "items",
      negative: "Allow negative stock",
      negativeDescription: "Allow outgoing quantities above available stock.",
      caution: "Caution",
    },
  },
  sw: {
    groups: { account: "Akaunti", workspace: "Eneo la kazi" },
    tabs: {
      profile: "Wasifu",
      general: "Jumla",
      notifications: "Arifa",
      inventory: "Bidhaa",
    },
    loading: "Inapakia mipangilio",
    saved: "Imehifadhiwa",
    saveFailed: "Imeshindikana kuhifadhi mpangilio.",
    profile: {
      detailsTitle: "Taarifa za wasifu",
      detailsDescription: "Sasisha taarifa zako binafsi na za mawasiliano.",
      firstName: "Jina la kwanza",
      lastName: "Jina la mwisho",
      email: "Barua pepe",
      phone: "Namba ya simu",
      save: "Hifadhi taarifa",
      saved: "Wasifu umesasishwa.",
      loadFailed: "Imeshindikana kupakia wasifu wako.",
      passwordTitle: "Badili nenosiri",
      passwordDescription: "Tumia nenosiri imara usilotumia mahali pengine.",
      oldPassword: "Nenosiri la zamani",
      newPassword: "Nenosiri jipya",
      confirmPassword: "Thibitisha nenosiri",
      changePassword: "Badili nenosiri",
      passwordConfirmTitle: "Ubadili nenosiri?",
      passwordConfirmDescription:
        "Vipindi vyako vya sasa vitaisha na utahitaji kuingia tena.",
      confirmChangePassword: "Thibitisha mabadiliko",
      passwordChanged: "Nenosiri limebadilishwa. Ingia tena.",
      dangerTitle: "Eneo hatari",
      dangerDescription: "Futa akaunti hii kabisa na uondoe ruhusa zake.",
      deleteAccount: "Futa akaunti",
      deleteBlocked: "Ongeza msimamizi mwingine kabla ya kufuta akaunti hii.",
      deleteDialogTitle: "Futa akaunti yako?",
      deleteDialogDescription:
        "Hatua hii haiwezi kutenduliwa. Weka nenosiri lako la sasa.",
      confirmDelete: "Futa kabisa",
      cancel: "Ghairi",
      logoutTitle: "Toka",
      logoutDescription: "Maliza kipindi hiki kwenye kifaa cha sasa.",
      logout: "Toka",
      logoutConfirmTitle: "Utoke sasa?",
      logoutConfirmDescription: "Utahitaji kuingiza nenosiri tena.",
      retry: "Jaribu tena",
      validation: {
        firstName: "Weka angalau herufi 2.",
        lastName: "Weka angalau herufi 2.",
        email: "Weka barua pepe halali.",
        phone: "Weka namba ya simu halali.",
        oldPassword: "Weka nenosiri la zamani.",
        newPassword: "Tumia herufi 8+, herufi kubwa na namba.",
        samePassword: "Chagua nenosiri tofauti na la zamani.",
        confirmPassword: "Nenosiri halilingani.",
        deletePassword: "Weka nenosiri lako la sasa.",
      },
    },
    general: {
      appearance: "Muonekano",
      appearanceDescription: "Chagua muonekano wa dashibodi kwenye kifaa hiki.",
      light: "Nyeupe",
      dark: "Nyeusi",
      system: "Mfumo",
      language: "Lugha",
      languageDescription: "Chagua lugha inayotumika kwenye dashibodi.",
      english: "English",
      swahili: "Kiswahili",
      compactTables: "Majedwali mafupi",
      compactTablesDescription: "Tumia nafasi ndogo kwenye majedwali.",
    },
    notifications: {
      lowStock: "Arifa za bidhaa chache",
      lowStockDescription: "Julisha bidhaa zikifikia kiwango chake.",
      sales: "Muhtasari wa mauzo",
      salesDescription: "Pokea muhtasari wa mauzo kila siku.",
      debt: "Vikumbusho vya madeni",
      debtDescription: "Kumbusha salio linalohitaji umakini.",
    },
    inventory: {
      threshold: "Kiwango cha bidhaa chache",
      thresholdDescription: "Kiwango cha bidhaa mpya.",
      items: "bidhaa",
      negative: "Ruhusu idadi hasi",
      negativeDescription: "Ruhusu bidhaa kutoka kuzidi kiasi kilichopo.",
      caution: "Tahadhari",
    },
  },
})

export type SettingsCopy = LocalizedCopy<
  (typeof settingsCopy)[Extract<LandingLocale, "en">]
>
