import type { LandingLocale } from "@/lib/landing-content"

export const outgoingDialogCopy = {
  en: {
    addTitle: "Record stock dispatch",
    addBtn: "Add Dispatch",
    addDescription: "Log parts leaving the stoo shelf for use, loss, or sales.",
    searchPlaceholder: "Search dispatches...",
    showing: "Showing",
    sort: "Sort",
    ascending: "Ascending",
    descending: "Descending",
    loadingTitle: "Loading dispatches...",
    loadingDescription: "Dispatch records are loading from the server.",
    loadErrorTitle: "Unable to load dispatches",
    emptyTitle: "No dispatches yet",
    emptyDescription: "Record a stock dispatch to start tracking outgoing items.",
    noResultsTitle: "No matching dispatches",
    noResultsDescription: "Try changing your search term.",
    viewTitle: "Dispatch details",
    viewDescription: "Log details of this stock dispatch.",
    dispatchNumber: "Dispatch number",
    dispatchNumberPlaceholder: "Auto-generated from timestamp milliseconds",
    manualDispatchNumberLabel: "Enter dispatch number manually",
    manualDispatchNumberDescription: "Keep this off to use the generated timestamp number. Turn it on only when the dispatch already has a business reference you need to record.",
    purpose: "Record Type",
    notes: "Notes",
    notesPlaceholder: "Add any extra details or notes",
    loggedBy: "Dispatched by",
    dispatchedAt: "Dispatched date & time",
    createdAt: "Created at",
    cancel: "Cancel",
    create: "Submit dispatch",
    close: "Close",
    createSuccess: "Stock dispatch record was logged successfully.",
    deleteTitle: "Delete dispatch log?",
    deleteDescription: "Are you sure you want to delete this dispatch? This will restore the stock quantities.",
    confirmDelete: "Delete",
    deleteSuccess: "Stock dispatch record was deleted.",
    partSearchPlaceholder: "Search part...",
    qtyLabel: "Qty",
    addRowBtn: "Add part",
    saleTitle: "Linked Sale Details",
    customerName: "Customer Name",
    paymentStatus: "Payment Status",
    paymentMethod: "Payment Method",
    amountPaid: "Amount Paid",
    grandTotal: "Grand Total",
    totalSaleValue: "Total Sale Value",
    partNameLabel: "Part Name",
    partNumberLabel: "No",
    skuLabel: "SKU",
    available: "Available",
    currentStock: "Current Stock",
    walkInCustomer: "Walk-in Customer",
    actions: "Actions",
    openActions: "Open dispatch actions",
    removePart: "Remove part",
    totalPartsDispatchedByQuantity: "Total parts dispatched (By Quantity)",
    salePriceLabel: "Sale Price",
    emptyPartsWarning: "Please add at least one part item to record dispatch.",
    validation: {
      purposeRequired: "Select a purpose.",
      dispatchedAtRequired: "Select the dispatched date.",
      partRequired: "Select a part.",
      qtyRequired: "Quantity must be at least 1.",
      unitPriceRequired: "Unit price is required for counter sales.",
      paymentStatusRequired: "Select payment status for sale.",
      paymentMethodRequired: "Select payment method for sale.",
    },
    insufficientStock: "Insufficient stock for",
    deleteError: "Failed to delete dispatch log.",
    changeBtn: "Change",
    unlinkSaleRecordBtn: "Unlink",
    statusPaid: "Paid",
    statusPending: "Pending",
    statusPartial: "Partial",
    methodCash: "Cash",
    methodMobileMoney: "Mobile Money",
    methodBankTransfer: "Bank Transfer",
    purposeSale: "Sale",
    purposeDamaged: "Damaged Goods",
    purposeReturn: "Return to Supplier",
    createSaleRecordBtn: "Create a Sale Record to continue",
    editSaleRecordBtn: "Edit Sale Record",
    saleLinkedTitle: "Sale Record Linked Successfully",
    saleRequiredError: "Please link a sale record to continue.",
    saleLinkedSuccess: "Sale details linked successfully.",
    saleLinkInstructions: "A sale record must be created and linked to complete this dispatch. Clicking the button below will open the Sales form.",
    parts: "Parts (Quantity)"
  },
  sw: {
    addTitle: "Sajili bidhaa zilizotoka stoo",
    addBtn: "Ongeza Utoaji",
    addDescription: "Sajili spea zinazoondoka stoo kwa matumizi, uharibifu, au mauzo.",
    searchPlaceholder: "Tafuta rekodi za utoaji...",
    showing: "Onyesha",
    sort: "Panga",
    parts: "Vipuli (Idadi)",
    ascending: "Kupanda",
    descending: "Kushuka",
    loadingTitle: "Rekodi za utoaji zinapakiwa...",
    loadingDescription: "Rekodi za utoaji zinapakiwa kutoka kwenye seva.",
    loadErrorTitle: "Imeshindikana kupakia rekodi za utoaji",
    emptyTitle: "Hakuna rekodi za utoaji bado",
    emptyDescription: "Sajili utoaji wa stoo ili kuanza kufuatilia bidhaa zinazotoka.",
    noResultsTitle: "Hakuna rekodi za utoaji zilizopatikana",
    noResultsDescription: "Jaribu kubadilisha neno la utafutaji.",
    viewTitle: "Maelezo ya utoaji",
    viewDescription: "Maelezo ya uandikishaji wa utoaji wa stoo hii.",
    dispatchNumber: "Namba ya utoaji (Dispatch)",
    dispatchNumberPlaceholder: "Inatengenezwa kwa timestamp ya millisekunde",
    manualDispatchNumberLabel: "Weka namba ya utoaji mwenyewe",
    manualDispatchNumberDescription: "Acha chaguo hili limezimwa kutumia namba iliyotengenezwa kiotomatiki. Washa tu kama tayari una rejea rasmi ya utoaji unayotaka kuandika.",
    purpose: "Aina ya Rekodi",
    notes: "Maelezo ya ziada",
    notesPlaceholder: "Weka maelezo yoyote ya ziada",
    loggedBy: "Imetolewa na",
    dispatchedAt: "Tarehe na muda wa kutoa",
    createdAt: "Tarehe ya kuundwa",
    cancel: "Ghairi",
    create: "Sajili utoaji",
    close: "Funga",
    createSuccess: "Utoaji wa stoo umesajiliwa kikamilifu.",
    deleteTitle: "Futa rekodi hii?",
    deleteDescription: "Una uhakika unataka kufuta utoaji huu? Hatua hii itarejesha idadi ya stoo iliyotolewa.",
    confirmDelete: "Futa",
    deleteSuccess: "Utoaji wa stoo umefutwa.",
    partSearchPlaceholder: "Tafuta spea/bidhaa...",
    qtyLabel: "Kiasi",
    addRowBtn: "Ongeza bidhaa",
    saleTitle: "Taarifa za Mauzo Yaliyounganishwa",
    customerName: "Jina la Mteja",
    paymentStatus: "Hali ya Malipo",
    paymentMethod: "Njia ya Malipo",
    amountPaid: "Kiasi Kilicholipwa",
    grandTotal: "Jumla Kuu",
    totalSaleValue: "Jumla ya Thamani ya Mauzo",
    partNameLabel: "Jina la Bidhaa",
    partNumberLabel: "Namba",
    skuLabel: "SKU",
    available: "Iliyopo",
    currentStock: "Stoo ya Sasa",
    walkInCustomer: "Mteja wa Dukani",
    actions: "Vitendo",
    openActions: "Fungua vitendo vya utoaji",
    removePart: "Ondoa bidhaa",
    totalPartsDispatchedByQuantity: "Jumla ya bidhaa zilizotolewa (Kwa Idadi)",
    salePriceLabel: "Bei ya Kuuza",
    emptyPartsWarning: "Tafadhali ongeza angalau bidhaa moja ili kusajili.",
    validation: {
      purposeRequired: "Chagua sababu ya kutoa.",
      dispatchedAtRequired: "Chagua tarehe ya kutoa.",
      partRequired: "Chagua spea/bidhaa.",
      qtyRequired: "Kiasi lazima kiwe angalau 1.",
      unitPriceRequired: "Bei ya bidhaa inahitajika kwa mauzo ya kaunta.",
      paymentStatusRequired: "Chagua hali ya malipo kwa ajili ya mauzo.",
      paymentMethodRequired: "Chagua njia ya malipo kwa ajili ya mauzo.",
    },
    insufficientStock: "Stoo haitoshi kwa",
    deleteError: "Imeshindikana kufuta rekodi ya utoaji.",
    changeBtn: "Badilisha",
    unlinkSaleRecordBtn: "Tenganisha",
    statusPaid: "Imelipwa",
    statusPending: "Inasubiri",
    statusPartial: "Sehemu",
    methodCash: "Taslimu",
    methodMobileMoney: "Pesa ya Simu",
    methodBankTransfer: "Uhamisho wa Benki",
    purposeSale: "Mauzo",
    purposeDamaged: "Bidhaa Zilizoharibika",
    purposeReturn: "Rudisha kwa Msambazaji",
    createSaleRecordBtn: "Sajili Mauzo ili kuendelea",
    editSaleRecordBtn: "Hariri Rekodi ya Mauzo",
    saleLinkedTitle: "Rekodi ya Mauzo Imeunganishwa Kikamilifu",
    saleRequiredError: "Tafadhali unganisha rekodi ya mauzo ili kuendelea.",
    saleLinkedSuccess: "Maelezo ya mauzo yameunganishwa kikamilifu.",
    saleLinkInstructions: "Lazima rekodi ya mauzo iundwe na kuunganishwa ili kukamilisha utoaji huu. Bonyeza kitufe hapa chini ili kufungua fomu ya mauzo.",
  },
} as const satisfies Record<LandingLocale, unknown>

export type OutgoingDialogCopy = (typeof outgoingDialogCopy)[LandingLocale]
