import type { LandingLocale } from "@/lib/landing-content"

export const outgoingDialogCopy = {
  en: {
    addTitle: "Record stock dispatch",
    addBtn: "Add Dispatch",
    addDescription: "Log parts leaving the stoo shelf for use, loss, or sales.",
    viewTitle: "Dispatch details",
    viewDescription: "Log details of this stock dispatch.",
    dispatchNumber: "Dispatch number",
    dispatchNumberPlaceholder: "Enter dispatch number (optional)",
    recipientName: "Recipient / Technician Name",
    recipientPlaceholder: "Enter name of person receiving stock",
    purpose: "Record Type",
    notes: "Notes",
    notesPlaceholder: "Add any extra details or notes",
    loggedBy: "Dispatched by",
    dispatchedAt: "Dispatched date & time",
    createdAt: "Created at",
    cancel: "Cancel",
    create: "Submit dispatch",
    close: "Close",
    createSuccess: "Stock dispatch record was logged successfully.",
    deleteTitle: "Delete dispatch log?",
    deleteDescription: "Are you sure you want to delete this dispatch? This will restore the stock quantities.",
    confirmDelete: "Delete",
    deleteSuccess: "Stock dispatch record was deleted.",
    partSearchPlaceholder: "Search part...",
    qtyLabel: "Qty",
    addRowBtn: "Add part",
    saleTitle: "Linked Sale Details",
    customerName: "Customer Name",
    paymentStatus: "Payment Status",
    paymentMethod: "Payment Method",
    amountPaid: "Amount Paid",
    salePriceLabel: "Sale Price",
    emptyPartsWarning: "Please add at least one part item to record dispatch.",
    validation: {
      purposeRequired: "Select a purpose.",
      dispatchedAtRequired: "Select the dispatched date.",
      partRequired: "Select a part.",
      qtyRequired: "Quantity must be at least 1.",
      paymentStatusRequired: "Select payment status for sale.",
      paymentMethodRequired: "Select payment method for sale.",
    },
    changeBtn: "Change",
    statusPaid: "Paid",
    statusPending: "Pending",
    statusPartial: "Partial",
    methodCash: "Cash",
    methodMobileMoney: "Mobile Money",
    methodBankTransfer: "Bank Transfer",
    purposeSale: "Sale",
    purposeTechnician: "Technician",
    purposeDamaged: "Damaged Goods",
    purposeReturn: "Return to Supplier",
    purposeTransfer: "Branch Transfer",
    createSaleRecordBtn: "Create a Sale Record to continue",
    editSaleRecordBtn: "Edit Sale Record",
    saleLinkedTitle: "Sale Record Linked Successfully",
    saleRequiredError: "Please link a sale record to continue.",
    saleLinkedSuccess: "Sale details linked successfully.",
    saleLinkInstructions: "A sale record must be created and linked to complete this dispatch. Clicking the button below will open the Sales form.",
  },
  sw: {
    addTitle: "Sajili bidhaa zilizotoka stoo",
    addBtn: "Ongeza Utoaji",
    addDescription: "Sajili spea zinazoondoka stoo kwa matumizi, uharibifu, au mauzo.",
    viewTitle: "Maelezo ya utoaji",
    viewDescription: "Maelezo ya uandikishaji wa utoaji wa stoo hii.",
    dispatchNumber: "Namba ya utoaji (Dispatch)",
    dispatchNumberPlaceholder: "Weka namba ya utoaji (si lazima)",
    recipientName: "Jina la mpokeaji / Fundi",
    recipientPlaceholder: "Weka jina la mtu anayepokea mzigo",
    purpose: "Aina ya Rekodi",
    notes: "Maelezo ya ziada",
    notesPlaceholder: "Weka maelezo yoyote ya ziada",
    loggedBy: "Imetolewa na",
    dispatchedAt: "Tarehe na muda wa kutoa",
    createdAt: "Tarehe ya kuundwa",
    cancel: "Ghairi",
    create: "Sajili utoaji",
    close: "Funga",
    createSuccess: "Utoaji wa stoo umesajiliwa kikamilifu.",
    deleteTitle: "Futa rekodi hii?",
    deleteDescription: "Una uhakika unataka kufuta utoaji huu? Hatua hii itarejesha idadi ya stoo iliyotolewa.",
    confirmDelete: "Futa",
    deleteSuccess: "Utoaji wa stoo umefutwa.",
    partSearchPlaceholder: "Tafuta spea/bidhaa...",
    qtyLabel: "Kiasi",
    addRowBtn: "Ongeza bidhaa",
    saleTitle: "Taarifa za Mauzo Yaliyounganishwa",
    customerName: "Jina la Mteja",
    paymentStatus: "Hali ya Malipo",
    paymentMethod: "Njia ya Malipo",
    amountPaid: "Kiasi Kilicholipwa",
    salePriceLabel: "Bei ya Kuuza",
    emptyPartsWarning: "Tafadhali ongeza angalau bidhaa moja ili kusajili.",
    validation: {
      purposeRequired: "Chagua sababu ya kutoa.",
      dispatchedAtRequired: "Chagua tarehe ya kutoa.",
      partRequired: "Chagua spea/bidhaa.",
      qtyRequired: "Kiasi lazima kiwe angalau 1.",
      paymentStatusRequired: "Chagua hali ya malipo kwa ajili ya mauzo.",
      paymentMethodRequired: "Chagua njia ya malipo kwa ajili ya mauzo.",
    },
    changeBtn: "Badilisha",
    statusPaid: "Imelipwa",
    statusPending: "Inasubiri",
    statusPartial: "Sehemu",
    methodCash: "Taslimu",
    methodMobileMoney: "Pesa ya Simu",
    methodBankTransfer: "Uhamisho wa Benki",
    purposeSale: "Mauzo",
    purposeTechnician: "Fundi",
    purposeDamaged: "Bidhaa Zilizoharibika",
    purposeReturn: "Rudisha kwa Msambazaji",
    purposeTransfer: "Uhamisho wa Tawi",
    createSaleRecordBtn: "Sajili Mauzo ili kuendelea",
    editSaleRecordBtn: "Hariri Rekodi ya Mauzo",
    saleLinkedTitle: "Rekodi ya Mauzo Imeunganishwa Kikamilifu",
    saleRequiredError: "Tafadhali unganisha rekodi ya mauzo ili kuendelea.",
    saleLinkedSuccess: "Maelezo ya mauzo yameunganishwa kikamilifu.",
    saleLinkInstructions: "Lazima rekodi ya mauzo iundwe na kuunganishwa ili kukamilisha utoaji huu. Bonyeza kitufe hapa chini ili kufungua fomu ya mauzo.",
  },
} as const satisfies Record<LandingLocale, unknown>

export type OutgoingDialogCopy = (typeof outgoingDialogCopy)[LandingLocale]

