import type { LandingLocale } from "@/lib/landing-content"

export const incomeStockDialogCopy = {
  en: {
    addTitle: "Record stock arrival",
    addBtn: "Add Intake",
    addDescription: "Log new shipment of parts into available inventory.",
    viewTitle: "Intake details",
    viewDescription: "Log details of this stock intake.",
    invoiceNumber: "Invoice number",
    invoiceNumberPlaceholder: "Enter invoice number (optional)",
    supplierName: "Supplier name",
    supplierNamePlaceholder: "Enter supplier name",
    receivedAt: "Received date & time",
    notes: "Notes",
    notesPlaceholder: "Add any extra details or notes",
    totalAmount: "Total intake cost",
    loggedBy: "Logged by",
    createdAt: "Created at",
    cancel: "Cancel",
    create: "Submit intake",
    close: "Close",
    createSuccess: "Stock intake record was logged successfully.",
    deleteTitle: "Delete intake log?",
    deleteDescription: "Are you sure you want to delete this intake? This will deduct the added stock quantities.",
    confirmDelete: "Delete",
    deleteSuccess: "Stock intake record was deleted.",
    partSearchPlaceholder: "Search part...",
    qtyLabel: "Qty",
    unitCostLabel: "Unit cost",
    subtotalLabel: "Subtotal",
    addRowBtn: "Add part",
    similarPartAlert: "There is a similar product in stock:",
    emptyPartsWarning: "Please add at least one part item to record intake.",
    validation: {
      supplierRequired: "Enter the supplier name.",
      receivedAtRequired: "Select the received date.",
      partRequired: "Select a part.",
      qtyRequired: "Quantity must be at least 1.",
      costRequired: "Unit cost must be at least 0.",
    },
  },
  sw: {
    addTitle: "Sajili mzigo mpya wa stoo",
    addBtn: "Ongeza Uingizaji",
    addDescription: "Ingiza bidhaa mpya za wasambazaji kwenye stoo inayopatikana.",
    viewTitle: "Maelezo ya mzigo",
    viewDescription: "Maelezo ya uingizaji wa stoo hii.",
    invoiceNumber: "Namba ya ankara (Invoice)",
    invoiceNumberPlaceholder: "Weka namba ya ankara (si lazima)",
    supplierName: "Jina la msambazaji",
    supplierNamePlaceholder: "Weka jina la msambazaji",
    receivedAt: "Tarehe na muda wa kupokea",
    notes: "Maelezo ya ziada",
    notesPlaceholder: "Weka maelezo yoyote ya ziada",
    totalAmount: "Gharama ya jumla ya uingizaji",
    loggedBy: "Imerekodiwa na",
    createdAt: "Tarehe ya kuundwa",
    cancel: "Ghairi",
    create: "Sajili uingizaji",
    close: "Funga",
    createSuccess: "Uingizaji wa stoo umesajiliwa kikamilifu.",
    deleteTitle: "Futa rekodi hii?",
    deleteDescription: "Una uhakika unataka kufuta uingizaji huu? Hatua hii itapunguza idadi ya stoo iliyoingizwa.",
    confirmDelete: "Futa",
    deleteSuccess: "Uingizaji wa stoo umefutwa.",
    partSearchPlaceholder: "Tafuta spea/bidhaa...",
    qtyLabel: "Kiasi",
    unitCostLabel: "Gharama ya kila kimoja",
    subtotalLabel: "Jumla ndogo",
    addRowBtn: "Ongeza bidhaa",
    similarPartAlert: "Kuna bidhaa inayofanana kwenye stoo:",
    emptyPartsWarning: "Tafadhali ongeza angalau bidhaa moja ili kusajili.",
    validation: {
      supplierRequired: "Weka jina la msambazaji.",
      receivedAtRequired: "Chagua tarehe ya kupokea.",
      partRequired: "Chagua spea/bidhaa.",
      qtyRequired: "Kiasi lazima kiwe angalau 1.",
      costRequired: "Gharama lazima iwe angalau 0.",
    },
  },
} as const satisfies Record<LandingLocale, unknown>

export type IncomeStockDialogCopy = (typeof incomeStockDialogCopy)[LandingLocale]
