import type { LandingLocale } from "@/lib/landing-content"

export const incomeStockDialogCopy = {
  en: {
    addTitle: "Record stock arrival",
    addBtn: "Add Intake",
    addDescription: "Log new shipment of parts into available inventory.",
    searchPlaceholder: "Search stock intakes...",
    showing: "Showing",
    sort: "Sort",
    ascending: "Ascending",
    descending: "Descending",
    loadingTitle: "Loading stock intakes...",
    loadingDescription: "Stock intake records are loading from the server.",
    loadErrorTitle: "Unable to load stock intakes",
    emptyTitle: "No stock intakes yet",
    emptyDescription: "Record a stock arrival to start tracking incoming items.",
    noResultsTitle: "No matching stock intakes",
    noResultsDescription: "Try changing your search term.",
    viewTitle: "Intake details",
    viewDescription: "Log details of this stock intake.",
    invoiceNumber: "Invoice number",
    invoiceNumberPlaceholder: "Enter invoice number (optional)",
    supplierName: "Supplier name",
    supplierNamePlaceholder: "Enter supplier name",
    supplierPhone: "Supplier phone",
    supplierPhonePlaceholder: "Enter supplier phone",
    debtToggle: "This stock intake is a debt",
    debtDescription: "Create a payable for the unpaid supplier balance from this intake.",
    debtDueDate: "Payment due date",
    debtAmountPaid: "Amount already paid",
    receivedAt: "Received date & time",
    notes: "Notes",
    notesPlaceholder: "Add any extra details or notes",
    totalAmount: "Total intake cost",
    loggedBy: "Logged by",
    createdAt: "Created at",
    cancel: "Cancel",
    create: "Submit intake",
    close: "Close",
    createSuccess: "Stock intake record was logged successfully.",
    deleteTitle: "Delete intake log?",
    deleteDescription: "Are you sure you want to delete this intake? This will deduct the added stock quantities.",
    confirmDelete: "Delete",
    deleteSuccess: "Stock intake record was deleted.",
    partSearchPlaceholder: "Search part...",
    partLabel: "Part",
    newPartLabel: "+ New Part",
    qtyLabel: "Qty",
    unitCostLabel: "Unit cost",
    subtotalLabel: "Subtotal",
    grandTotal: "Grand Total",
    totalPartsByQuantity: "Total parts received (By Quantity)",
    partNameLabel: "Part Name",
    partNumberLabel: "No",
    skuLabel: "SKU",
    currentStock: "Current Stock",
    stockLabel: "Stock",
    matchingProducts: "Matching Products",
    select: "Select",
    actions: "Actions",
    openActions: "Open stock intake actions",
    removePart: "Remove part",
    addRowBtn: "Add part",
    changeBtn: "Change",
    similarPartAlert: "There is a similar product in stock:",
    emptyPartsWarning: "Please add at least one part item to record intake.",
    deleteError: "Failed to delete stock intake.",
    validation: {
      supplierRequired: "Enter the supplier name.",
      receivedAtRequired: "Select the received date.",
      partRequired: "Select a part.",
      qtyRequired: "Quantity must be at least 1.",
      costRequired: "Unit cost must be at least 0.",
      debtPhoneRequired: "Enter the supplier's phone number for a debt intake.",
      debtAmountInvalid: "Amount already paid must be at least 0 and less than the total intake cost.",
    },
  },
  sw: {
    addTitle: "Sajili mzigo mpya wa stoo",
    addBtn: "Ongeza Uingizaji",
    addDescription: "Ingiza bidhaa mpya za wasambazaji kwenye stoo inayopatikana.",
    searchPlaceholder: "Tafuta rekodi za uingizaji...",
    showing: "Onyesha",
    sort: "Panga",
    ascending: "Kupanda",
    descending: "Kushuka",
    loadingTitle: "Rekodi za uingizaji zinapakiwa...",
    loadingDescription: "Rekodi za uingizaji zinapakiwa kutoka kwenye seva.",
    loadErrorTitle: "Imeshindikana kupakia rekodi za uingizaji",
    emptyTitle: "Hakuna rekodi za uingizaji bado",
    emptyDescription: "Sajili mzigo wa stoo ili kuanza kufuatilia bidhaa zinazoingia.",
    noResultsTitle: "Hakuna rekodi za uingizaji zilizopatikana",
    noResultsDescription: "Jaribu kubadilisha neno la utafutaji.",
    viewTitle: "Maelezo ya mzigo",
    viewDescription: "Maelezo ya uingizaji wa stoo hii.",
    invoiceNumber: "Namba ya ankara (Invoice)",
    invoiceNumberPlaceholder: "Weka namba ya ankara (si lazima)",
    supplierName: "Jina la msambazaji",
    supplierNamePlaceholder: "Weka jina la msambazaji",
    supplierPhone: "Simu ya msambazaji",
    supplierPhonePlaceholder: "Weka namba ya simu ya msambazaji",
    debtToggle: "Uingizaji huu wa stoo ni wa deni",
    debtDescription: "Unda deni la kulipa kwa salio la msambazaji ambalo halijalipwa.",
    debtDueDate: "Tarehe ya mwisho ya malipo",
    debtAmountPaid: "Kiasi kilicholipwa tayari",
    receivedAt: "Tarehe na muda wa kupokea",
    notes: "Maelezo ya ziada",
    notesPlaceholder: "Weka maelezo yoyote ya ziada",
    totalAmount: "Gharama ya jumla ya uingizaji",
    loggedBy: "Imerekodiwa na",
    createdAt: "Tarehe ya kuundwa",
    cancel: "Ghairi",
    create: "Sajili uingizaji",
    close: "Funga",
    createSuccess: "Uingizaji wa stoo umesajiliwa kikamilifu.",
    deleteTitle: "Futa rekodi hii?",
    deleteDescription: "Una uhakika unataka kufuta uingizaji huu? Hatua hii itapunguza idadi ya stoo iliyoingizwa.",
    confirmDelete: "Futa",
    deleteSuccess: "Uingizaji wa stoo umefutwa.",
    partSearchPlaceholder: "Tafuta spea/bidhaa...",
    partLabel: "Spea / Bidhaa",
    newPartLabel: "+ Spea Mpya",
    qtyLabel: "Kiasi",
    unitCostLabel: "Gharama ya kila kimoja",
    subtotalLabel: "Jumla ndogo",
    grandTotal: "Jumla Kuu",
    totalPartsByQuantity: "Jumla ya bidhaa zilizopokelewa (Kwa Idadi)",
    partNameLabel: "Jina la Bidhaa",
    partNumberLabel: "Namba",
    skuLabel: "SKU",
    currentStock: "Stoo ya Sasa",
    stockLabel: "Stoo",
    matchingProducts: "Bidhaa Zinazofanana",
    select: "Chagua",
    actions: "Vitendo",
    openActions: "Fungua vitendo vya uingizaji",
    removePart: "Ondoa bidhaa",
    addRowBtn: "Ongeza bidhaa",
    changeBtn: "Badilisha",
    similarPartAlert: "Kuna bidhaa inayofanana kwenye stoo:",
    emptyPartsWarning: "Tafadhali ongeza angalau bidhaa moja ili kusajili.",
    deleteError: "Imeshindikana kufuta rekodi ya uingizaji.",
    validation: {
      supplierRequired: "Weka jina la msambazaji.",
      receivedAtRequired: "Chagua tarehe ya kupokea.",
      partRequired: "Chagua spea/bidhaa.",
      qtyRequired: "Kiasi lazima kiwe angalau 1.",
      costRequired: "Gharama lazima iwe angalau 0.",
      debtPhoneRequired: "Weka namba ya simu ya msambazaji kwa uingizaji wa deni.",
      debtAmountInvalid: "Kiasi kilicholipwa lazima kiwe kuanzia 0 na chini ya gharama ya jumla.",
    },
  },
} as const satisfies Record<LandingLocale, unknown>

export type IncomeStockDialogCopy = (typeof incomeStockDialogCopy)[LandingLocale]
